"""palace2_hookdata.py — the PALACE II hook data for BP-02 (proposal; nothing is written into a pack).

Reads the 16 piece manifests + palace2_group.json in _staging/palace231/_gen and writes, next to them:
  * palace2_buildings_entries.json — the 16 CIV_BUILDINGS entries (same rules as tools/civ_village_data.py:
    lids, door, work, dir, bom, chests; art [] until the gallery pass hangs the palace)
  * pw_civ_court_data.js           — PALACE_BEDS_2 keyed "00".."33" (r = depth from the gate, c = frontage) beside the frozen
                                      2 x 2 table PALACE_BEDS_1 (1.3.232: a saved world's 2 x 2 palace keeps its role beds)
  * palace2_secrets.json            — the secret-passage table (41 rows)
  * pw_civ_palace_secrets_data.js   — 1.3.232 (#21 Part D): the same rows as a data module for pw_civ_palace_secrets.js

Usage: python3 tools/palace2_hookdata.py [--no-bom]
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, "/home/claude/tools")
import civ_village_data as CVD  # noqa: E402

GEN = Path("/home/claude/_staging/palace231/_gen")
OUT = Path("/home/claude/_staging/palace231")
COURT_ROLES = ("lord", "noble", "servant", "guard", "clerk", "cell", "child")
# 1.3.232 (#21): the 2 x 2 palace's role beds (tools/palace_beds.py, 1.3.229) — frozen: that model is no longer generated, but
# every saved world that holds one reads them (pw_civ_court.js bedsOfPiece by piece key; the keys never collide with "rc")
LEGACY_BEDS = {"ne": {"child": 4, "guard": 4, "lord": 1, "noble": 3, "servant": 4}, "nw": {"child": 3, "noble": 3, "servant": 12},
               "se": {"child": 5, "clerk": 7, "guard": 3, "noble": 5, "servant": 22}, "sw": {"cell": 4, "clerk": 7, "guard": 9, "servant": 16}}
SECRET_MODES = {"disguised", "hidden", "oneway", "lore"}


def entry(manifest, with_bom):
    """One CIV_BUILDINGS entry from one piece manifest (mirrors civ_village_data.table)."""
    m = manifest
    stem = m["name"].split(":", 1)[1]
    ents = m["entities"]
    out = {
        "stem": stem, "size": m["size"], "datum_y": m["datum_y"], "stages": 5,
        "lids": [[*e["cell"], e["hinge"]] for e in ents if e["id"] == "pw:hatch_lid"],
        "door": next((e["cell"] for e in ents if e.get("fam") == "datum"), [0, 0, m["size"][2] // 2]),
        "work": sum(1 for e in ents if e.get("fam") == "station" and e.get("kind") not in ("door", "bed", "seat", "store")),
        "dir": [[x, y, z, n, {k: v for k, v in s.items() if k in CVD.DIRK}] for x, y, z, n, s in m["blocks"] if set(s) & CVD.DIRK],
        "chests": sorted([[x, y, z, n] for x, y, z, n, s in m["blocks"] if n in ("minecraft:chest", "minecraft:barrel")],
                         key=lambda c: (abs(c[1] - m["datum_y"]), c[1], c[0], c[2])),
        "art": [],
        "palace2": {"grid": m["grid"]},
    }
    if with_bom:
        out["bom"] = CVD.bom_of(stem)
    return out


def main():
    with_bom = "--no-bom" not in sys.argv
    CVD.STAGES = GEN / "stages"
    group = json.loads((GEN / "palace2_group.json").read_text())
    table, beds = {}, {}
    for piece in group["pieces"]:
        r, c = piece["grid"]
        m = json.loads((GEN / "manifests" / f"{piece['stem']}.json").read_text())
        assert m["grid"] == piece["grid"] and m["size"] == [64, 50, 64], piece["stem"]
        table[m["name"]] = entry(m, with_bom)
        unknown = set(piece["beds"]) - set(COURT_ROLES)
        assert not unknown, f"{piece['stem']}: bed roles outside the court's set: {unknown}"
        beds[f"{r}{c}"] = dict(sorted(piece["beds"].items()))
    assert len(table) == 16 and sorted(beds) == [f"{r}{c}" for r in range(4) for c in range(4)]
    # D-GH1007-LORDBEDS (his ruling 10-07: "at least 2 — it's supposed to house a court")
    assert sum(b.get("lord", 0) for b in beds.values()) >= 2, "PALACE II must hold at least 2 lord's beds"
    (OUT / "palace2_buildings_entries.json").write_text(json.dumps(table, separators=(",", ":")))
    (OUT / "pw_civ_court_data.js").write_text(
        "// pw_civ_court_data.js — the palace pieces' beds by room role. A bed = one double bed (2 bed blocks).\n"
        "// Roles: lord, noble, servant, guard, clerk, cell (never a home), child (a children's bed, never a role slot).\n"
        "// GENERATED by tools/palace2_hookdata.py. PALACE_BEDS_1: the 2 x 2 palace (tools/palace_beds.py 1.3.229, frozen),\n"
        "// keyed sw se nw ne; PALACE_BEDS_2: PALACE II, keyed \"rc\" (r = depth from the gate side 0..3, c = frontage 0..3).\n"
        "export const PALACE_BEDS_1 = " + json.dumps(LEGACY_BEDS) + ";\n"
        "export const PALACE_BEDS_2 = " + json.dumps(beds) + ";\n"
        "export const PALACE_BEDS = { ...PALACE_BEDS_1, ...PALACE_BEDS_2 };\n")
    rows = [{k: s[k] for k in ("id", "element", "public", "hidden", "mode")} for s in group["secrets"]]
    for s in rows:
        assert s["mode"] in SECRET_MODES, s["id"]
        for k in ("public", "hidden"):
            c = s[k]
            assert c is None or (len(c) == 3 and 0 <= c[0] < 256 and 0 <= c[2] < 256 and -15 <= c[1] <= 34), (s["id"], k, c)
    (OUT / "palace2_secrets.json").write_text(json.dumps(rows, indent=0))
    (OUT / "pw_civ_palace_secrets_data.js").write_text(
        "// pw_civ_palace_secrets_data.js — GENERATED by tools/palace2_hookdata.py from palace2_group.json (PALACE II): the hidden\n"
        "// network's ends in MODEL cells [x = depth from the gate, f = feet over the court, z = frontage].\n"
        "// mode: disguised | hidden (two-way) · oneway (an iron door that opens from ONE side) · lore (no way through). Do not edit by hand.\n"
        "export const PALACE_SECRETS = [\n" + ",\n".join("  " + json.dumps(s, ensure_ascii=False) for s in rows) + "\n];\n", encoding="utf-8")
    tot = {}
    for b in beds.values():
        for k, v in b.items():
            tot[k] = tot.get(k, 0) + v
    print(f"16 entries ({sum(len(e['dir']) for e in table.values())} dir cells, {sum(len(e['chests']) for e in table.values())} chests, "
          f"work {sum(e['work'] for e in table.values())}, bom {'yes' if with_bom else 'NO'}); beds {tot}; secrets {len(group['secrets'])}")


if __name__ == "__main__":
    main()
