"""palace2_secrets_js.py — palace2_secrets.json (tools/palace2_hookdata.py) -> scripts/pw_civ_palace_secrets_data.js.

1.3.232 (#21 Part D): the secret-passage table as a data module for pw_civ_palace_secrets.js. Rows are copied as they are
(id, element, public [x, f, z], hidden [x, f, z] | null, mode); cells are PALACE II model cells: x = depth from the gate
(0..255), f = feet over the court (0 = the paving), z = frontage (0..255).
Usage: python3 palace2_secrets_js.py <palace2_secrets.json> <out.js>
"""
import json
import sys

MODES = {"disguised", "hidden", "oneway", "lore"}


def main(src, out):
    rows = json.load(open(src, encoding="utf-8"))
    assert isinstance(rows, list) and rows, "no rows"
    keep = []
    for r in rows:
        assert r["mode"] in MODES, r
        for k in ("public", "hidden"):
            c = r[k]
            assert c is None or (len(c) == 3 and all(isinstance(v, int) for v in c)), (r["id"], k, c)
            if c is not None:
                assert 0 <= c[0] < 256 and 0 <= c[2] < 256 and -15 <= c[1] <= 34, (r["id"], k, c)
        keep.append({k: r[k] for k in ("id", "element", "public", "hidden", "mode")})
    body = ",\n".join("  " + json.dumps(r, ensure_ascii=False) for r in keep)
    with open(out, "w", encoding="utf-8") as f:
        f.write("// pw_civ_palace_secrets_data.js — GENERATED by palace2_secrets_js.py from palace2_secrets.json (tools/palace2_hookdata.py,\n"
                "// PALACE II, 41 rows): the hidden network's ends in MODEL cells [x = depth from the gate, f = feet over the court, z = frontage].\n"
                "// mode: disguised | hidden (two-way) · oneway (an iron door that opens from ONE side) · lore (no way through). Do not edit by hand.\n"
                "export const PALACE_SECRETS = [\n" + body + "\n];\n")
    print(f"{len(keep)} rows -> {out}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
