source=skybox:the_end/sky004_end_barrens.png
startFadeIn=11:58
endFadeIn=11:59
startFadeOut=12:00
endFadeOut=12:01
blend=alpha
rotate=true
speed=1
axis=0.0 0.93969 0.34202
transition=10
biomes=end_barrens