// pw_testrunner_bump.js — lineup "bump" THE BUMP-MAP TEST (its own lineup, his BT1) (PW-TestRunner BP v0.5.11).
// /scriptevent pw:test start bump — RP-06 1.4.28 + RP-07 1.4.43 + RP-08 1.4.9 + RP-04 1.3.144 + BP-02 1.3.200 + StripMine BP 1.3.12. Generated by tools/build_p20.py.
function lines(text) {
  const out = [];
  for (const para of String(text).split("\n")) {
    let cur = "";
    for (const piece of para.split(/(?<=[.!?:]) +| (?=- )/)) {
      if (cur && (cur + " " + piece).length > 190) { out.push(cur); cur = piece; } else cur = cur ? cur + " " + piece : piece;
    }
    if (cur) out.push(cur);
  }
  return out.join("\n");
}
const CLEAR = ["fill ~-12 ~ ~-14 ~12 ~7 ~-2 air"];
const LOOK = "Look for: each animal drawn whole (no missing parts, no purple-black checker texture, no floating), its name tag, a sensible size next to you; " +
  "tap one to hear it. They are held still (idle animation only).";
const PASSN = "PASS = all right. FAIL + note = which one (its name tag) and what (use all 3 note boxes if needed). A preference (keep / drop one) also goes in a note.";
export const BUMP_DATA = [
 {
  "id": "m01",
  "group": "BUMP",
  "title": "BUMP MAPS: SAME MOB WITH / WITHOUT THE NORMAL MAP",
  "look": "LEFT to RIGHT in pairs (ON / OFF): warden, dolphin, turtle, blue parrot. Colour and shine are identical; only the normal (bump) map differs. Look at them in sun and in shade, close up: do the ON copies show raised / sunken detail that the OFF copies lack? PASS = a visible, useful difference. FAIL = no difference (bump maps not worth it).",
  "rig": {
   "mob": "pw:nbump",
   "event": "pw:v0",
   "name": "Warden - bump ON",
   "label": "warden - bump on",
   "half": 13,
   "halfz": 3,
   "height": 5,
   "roof": false,
   "row": [
    {
     "mob": "pw:nbump",
     "dx": 3,
     "event": "pw:v1",
     "name": "Warden - bump OFF",
     "label": "warden - bump off"
    },
    {
     "mob": "pw:nbump",
     "dx": 6,
     "event": "pw:v2",
     "name": "Dolphin - bump ON",
     "label": "dolphin - bump on"
    },
    {
     "mob": "pw:nbump",
     "dx": 9,
     "event": "pw:v3",
     "name": "Dolphin - bump OFF",
     "label": "dolphin - bump off"
    },
    {
     "mob": "pw:nbump",
     "dx": 12,
     "event": "pw:v4",
     "name": "Turtle - bump ON",
     "label": "turtle - bump on"
    },
    {
     "mob": "pw:nbump",
     "dx": 15,
     "event": "pw:v5",
     "name": "Turtle - bump OFF",
     "label": "turtle - bump off"
    },
    {
     "mob": "pw:nbump",
     "dx": 18,
     "event": "pw:v6",
     "name": "Parrot - bump ON",
     "label": "parrot - bump on"
    },
    {
     "mob": "pw:nbump",
     "dx": 21,
     "event": "pw:v7",
     "name": "Parrot - bump OFF",
     "label": "parrot - bump off"
    }
   ]
  }
 }
];
const Q0 = { id: "q0", group: "BUMP SETUP", title: "BUMP: PHONE HOSTS, PS5 JOINS (VIBRANT VISUALS), FLAT GROUND, FACE NORTH",
  body: lines("Packs (on the phone): RP-06 1.4.28 + RP-07 1.4.43 + RP-08 1.4.9 + RP-04 1.3.144 + BP-02 1.3.200 + StripMine BP 1.3.12 - always together; PW-TestRunner BP v0.5.11 at the bottom. " +
    "Use a COPY of the test world; host on the phone, join on the PS5 with Vibrant Visuals ON. Creative.\n" +
    "Content log after load: 'PW Test Runner BP v0.5.11'.\nStand on big FLAT open ground (15 blocks clear each side, 15 NORTH) and FACE NORTH.\nPASS = ready."),
  setup: [{ daytime: "noon" }, { weather: "clear" }] };
const STEPSBUMP = BUMP_DATA.map((d) => ({ id: d.id, group: d.group, title: d.title,
  body: lines(`${d.look}\n${LOOK}\nSHOT of the pen from the front (south).\n${PASSN}`), setup: d.rig ? [{ cmd: CLEAR }, { rig: d.rig }] : [{ cmd: CLEAR }] }));
const Q9 = { id: "q9", group: "BUMP DONE", title: "BUMP: ALL CLEAR - UPLOAD",
  body: lines("The last pen is removed when you pass this step. Upload any shots and copy the content log (or /scriptevent pw:test report bump).\nPASS = uploaded (or about to)."),
  setup: [{ cmd: CLEAR }, { daytime: "noon" }] };
export const BUMP_STEPS = [Q0, ...STEPSBUMP, Q9];
export const BUMP_INDEX = Object.fromEntries(BUMP_STEPS.map((s, i) => [s.id, i]));
