// pw_testrunner_p19.js — lineup "p19" THE PICKS PARADE (PW-TestRunner BP v0.5.7, D-C353/D-C355; menagerie wave P3, his picks 22:00-22:42 CT 09-30).
// /scriptevent pw:test start p19 — RP-07 v1.4.34 + PW-StripMine BP v1.3.9: every version he kept (ids pw:<animal>_<pack>), grouped by
// animal so the versions stand side by side; name tags = name (PACK); gorilla / boar / bear pens also hold OUR creature.
// Generated by tools/build_p19.py. The rig (pw_testrunner_rig.js) spawns them; a missing creature is logged ('RIG ... FAILED').
function lines(text) {
  const out = [];
  for (const para of String(text).split("\n")) {
    let cur = "";
    for (const piece of para.split(/(?<=[.!?:]) +| (?=- )/)) {
      if (cur && (cur + " " + piece).length > 190) { out.push(cur); cur = piece; } else cur = cur ? cur + " " + piece : piece;
    }
    if (cur) out.push(cur);
  }
  return out.join("\n");
}
const CLEAR = ["fill ~-12 ~ ~-14 ~12 ~7 ~-2 air"];
const LOOK = "Look for: each animal drawn whole (no missing parts, no purple-black checker texture, no floating), its name tag, a sensible size next to you; " +
  "tap one to hear it. They are held still (idle animation only).";
const PASSN = "PASS = all right. FAIL + note = which one (its name tag) and what (use all 3 note boxes if needed). A preference (keep / drop one) also goes in a note.";
export const P19_DATA = [
 {
  "id": "b01",
  "group": "P19 HIS PICKS",
  "title": "AARDVARK \u00b7 ALLIGATOR",
  "look": "LEFT to RIGHT: AARDVARK (YSAV), ALLIGATOR ALBINO (ANF), ALLIGATOR AMERICAN (ANF), ALLIGATOR CHINESE (ANF), ALLIGATOR (YTRI).",
  "rig": {
   "mob": "pw:alligator_american_anf",
   "label": "alligator american (anf)",
   "name": "Alligator American (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:aardvark_ysav",
     "dx": -8,
     "label": "aardvark (ysav)",
     "name": "Aardvark (YSav)"
    },
    {
     "mob": "pw:alligator_albino_anf",
     "dx": -4,
     "label": "alligator albino (anf)",
     "name": "Alligator Albino (AnF)"
    },
    {
     "mob": "pw:alligator_chinese_anf",
     "dx": 4,
     "label": "alligator chinese (anf)",
     "name": "Alligator Chinese (AnF)"
    },
    {
     "mob": "pw:alligator_ytri",
     "dx": 8,
     "label": "alligator (ytri)",
     "name": "Alligator (YTri)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b02",
  "group": "P19 HIS PICKS",
  "title": "ANT \u00b7 ANTEATER \u00b7 BABOON",
  "look": "LEFT to RIGHT: ANT (WA), ANTEATER (YTRI), BABOON (YSAV).",
  "rig": {
   "mob": "pw:anteater_ytri",
   "label": "anteater (ytri)",
   "name": "Anteater (YTri)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:ant_wa",
     "dx": -4,
     "label": "ant (wa)",
     "name": "Ant (WA)"
    },
    {
     "mob": "pw:baboon_ysav",
     "dx": 4,
     "label": "baboon (ysav)",
     "name": "Baboon (YSav)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b03",
  "group": "P19 HIS PICKS",
  "title": "BEAR",
  "look": "LEFT to RIGHT: BLACK BEAR (OURS), BEAR BLACK (ANF), BEAR GRIZZLY (ANF), GRIZZLY BEAR (OURS). The AnF bears were scaled to OUR bears' length (his 'keep our size'): compare them with ours (OURS).",
  "rig": {
   "mob": "pw:bear_grizzly_anf",
   "label": "bear grizzly (anf)",
   "name": "Bear Grizzly (AnF)",
   "half": 11,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "sf_nba:black_bear",
     "dx": -10,
     "label": "black bear (ours)",
     "name": "Black Bear (OURS)"
    },
    {
     "mob": "pw:bear_black_anf",
     "dx": -5,
     "label": "bear black (anf)",
     "name": "Bear Black (AnF)"
    },
    {
     "mob": "sf_nba:grizzly_bear",
     "dx": 5,
     "label": "grizzly bear (ours)",
     "name": "Grizzly Bear (OURS)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b04",
  "group": "P19 HIS PICKS",
  "title": "BEAVER",
  "look": "LEFT to RIGHT: BEAVER (ANF).",
  "rig": {
   "mob": "pw:beaver_anf",
   "label": "beaver (anf)",
   "name": "Beaver (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b05",
  "group": "P19 HIS PICKS",
  "title": "BEETLE",
  "look": "LEFT to RIGHT: BEETLE ATLAS (ANF), BEETLE COLORADOPOTATO (ANF), BEETLE DESERT (ANF), BEETLE ELEPHANT (ANF), BEETLE HERCULES (ANF).",
  "rig": {
   "mob": "pw:beetle_desert_anf",
   "label": "beetle desert (anf)",
   "name": "Beetle Desert (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:beetle_atlas_anf",
     "dx": -8,
     "label": "beetle atlas (anf)",
     "name": "Beetle Atlas (AnF)"
    },
    {
     "mob": "pw:beetle_coloradopotato_anf",
     "dx": -4,
     "label": "beetle coloradopotato (anf)",
     "name": "Beetle Coloradopotato (AnF)"
    },
    {
     "mob": "pw:beetle_elephant_anf",
     "dx": 4,
     "label": "beetle elephant (anf)",
     "name": "Beetle Elephant (AnF)"
    },
    {
     "mob": "pw:beetle_hercules_anf",
     "dx": 8,
     "label": "beetle hercules (anf)",
     "name": "Beetle Hercules (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b06",
  "group": "P19 HIS PICKS",
  "title": "BEETLE",
  "look": "LEFT to RIGHT: BEETLE MEXICANBEAN (ANF), BEETLE MOUNTAINPINE (ANF), BEETLE STAG (ANF).",
  "rig": {
   "mob": "pw:beetle_mountainpine_anf",
   "label": "beetle mountainpine (anf)",
   "name": "Beetle Mountainpine (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:beetle_mexicanbean_anf",
     "dx": -4,
     "label": "beetle mexicanbean (anf)",
     "name": "Beetle Mexicanbean (AnF)"
    },
    {
     "mob": "pw:beetle_stag_anf",
     "dx": 4,
     "label": "beetle stag (anf)",
     "name": "Beetle Stag (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b07",
  "group": "P19 HIS PICKS",
  "title": "BLUE JAY",
  "look": "LEFT to RIGHT: BLUE JAY (WA).",
  "rig": {
   "mob": "pw:blue_jay_wa",
   "label": "blue jay (wa)",
   "name": "Blue Jay (WA)",
   "half": 10,
   "halfz": 3,
   "height": 6,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b08",
  "group": "P19 HIS PICKS",
  "title": "BOAR",
  "look": "LEFT to RIGHT: BOAR (IFS), BOAR (WA), BOAR (YSAV), BOAR (OURS). His three boars next to ours (OURS): is each better than ours?",
  "rig": {
   "mob": "pw:boar_ysav",
   "label": "boar (ysav)",
   "name": "Boar (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:boar_ifs",
     "dx": -8,
     "label": "boar (ifs)",
     "name": "Boar (IFS)"
    },
    {
     "mob": "pw:boar_wa",
     "dx": -4,
     "label": "boar (wa)",
     "name": "Boar (WA)"
    },
    {
     "mob": "sf_nba:boar",
     "dx": 4,
     "label": "boar (ours)",
     "name": "Boar (OURS)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b09",
  "group": "P19 HIS PICKS",
  "title": "BUFFALO",
  "look": "LEFT to RIGHT: BUFFALO (YSAV).",
  "rig": {
   "mob": "pw:buffalo_ysav",
   "label": "buffalo (ysav)",
   "name": "Buffalo (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b10",
  "group": "P19 HIS PICKS",
  "title": "BUTTERFLY",
  "look": "LEFT to RIGHT: BUTTERFLY ADONISBLUE (ANF), BUTTERFLY BLUEMORPHO (ANF), BUTTERFLY CRIMSONROSE (ANF), BUTTERFLY EMERALDSWALLOWTAIL (ANF), BUTTERFLY GIANTAFRICAN (ANF).",
  "rig": {
   "mob": "pw:butterfly_crimsonrose_anf",
   "label": "butterfly crimsonrose (anf)",
   "name": "Butterfly Crimsonrose (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:butterfly_adonisblue_anf",
     "dx": -8,
     "label": "butterfly adonisblue (anf)",
     "name": "Butterfly Adonisblue (AnF)"
    },
    {
     "mob": "pw:butterfly_bluemorpho_anf",
     "dx": -4,
     "label": "butterfly bluemorpho (anf)",
     "name": "Butterfly Bluemorpho (AnF)"
    },
    {
     "mob": "pw:butterfly_emeraldswallowtail_anf",
     "dx": 4,
     "label": "butterfly emeraldswallowtail (anf)",
     "name": "Butterfly Emeraldswallowtail (AnF)"
    },
    {
     "mob": "pw:butterfly_giantafrican_anf",
     "dx": 8,
     "label": "butterfly giantafrican (anf)",
     "name": "Butterfly Giantafrican (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b11",
  "group": "P19 HIS PICKS",
  "title": "BUTTERFLY",
  "look": "LEFT to RIGHT: BUTTERFLY GOLIATHBIRDWING (ANF), BUTTERFLY MONARCH (ANF), BUTTERFLY QUEENALEXANDRA (ANF).",
  "rig": {
   "mob": "pw:butterfly_monarch_anf",
   "label": "butterfly monarch (anf)",
   "name": "Butterfly Monarch (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:butterfly_goliathbirdwing_anf",
     "dx": -4,
     "label": "butterfly goliathbirdwing (anf)",
     "name": "Butterfly Goliathbirdwing (AnF)"
    },
    {
     "mob": "pw:butterfly_queenalexandra_anf",
     "dx": 4,
     "label": "butterfly queenalexandra (anf)",
     "name": "Butterfly Queenalexandra (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b12",
  "group": "P19 HIS PICKS",
  "title": "CAPUCHIN \u00b7 CASSOWARY",
  "look": "LEFT to RIGHT: CAPUCHIN (WA), CASSOWARY (YTRI).",
  "rig": {
   "mob": "pw:cassowary_ytri",
   "label": "cassowary (ytri)",
   "name": "Cassowary (YTri)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:capuchin_wa",
     "dx": -4,
     "label": "capuchin (wa)",
     "name": "Capuchin (WA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b13",
  "group": "P19 HIS PICKS",
  "title": "CATERPILLAR",
  "look": "LEFT to RIGHT: CATERPILLAR ADONISBLUE (ANF), CATERPILLAR BLUEMORPHO (ANF), CATERPILLAR CRIMSONROSE (ANF), CATERPILLAR EMERALDSWALLOWTAIL (ANF), CATERPILLAR GIANTAFRICAN (ANF).",
  "rig": {
   "mob": "pw:caterpillar_crimsonrose_anf",
   "label": "caterpillar crimsonrose (anf)",
   "name": "Caterpillar Crimsonrose (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:caterpillar_adonisblue_anf",
     "dx": -8,
     "label": "caterpillar adonisblue (anf)",
     "name": "Caterpillar Adonisblue (AnF)"
    },
    {
     "mob": "pw:caterpillar_bluemorpho_anf",
     "dx": -4,
     "label": "caterpillar bluemorpho (anf)",
     "name": "Caterpillar Bluemorpho (AnF)"
    },
    {
     "mob": "pw:caterpillar_emeraldswallowtail_anf",
     "dx": 4,
     "label": "caterpillar emeraldswallowtail (anf)",
     "name": "Caterpillar Emeraldswallowtail (AnF)"
    },
    {
     "mob": "pw:caterpillar_giantafrican_anf",
     "dx": 8,
     "label": "caterpillar giantafrican (anf)",
     "name": "Caterpillar Giantafrican (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b14",
  "group": "P19 HIS PICKS",
  "title": "CATERPILLAR",
  "look": "LEFT to RIGHT: CATERPILLAR GOLIATHBIRDWING (ANF), CATERPILLAR MONARCH (ANF), CATERPILLAR QUEENALEXANDRA (ANF).",
  "rig": {
   "mob": "pw:caterpillar_monarch_anf",
   "label": "caterpillar monarch (anf)",
   "name": "Caterpillar Monarch (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:caterpillar_goliathbirdwing_anf",
     "dx": -4,
     "label": "caterpillar goliathbirdwing (anf)",
     "name": "Caterpillar Goliathbirdwing (AnF)"
    },
    {
     "mob": "pw:caterpillar_queenalexandra_anf",
     "dx": 4,
     "label": "caterpillar queenalexandra (anf)",
     "name": "Caterpillar Queenalexandra (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b15",
  "group": "P19 HIS PICKS",
  "title": "CHIMPANZEE \u00b7 COYOTE",
  "look": "LEFT to RIGHT: CHIMPANZEE (WA), COYOTE (YTRI).",
  "rig": {
   "mob": "pw:coyote_ytri",
   "label": "coyote (ytri)",
   "name": "Coyote (YTri)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:chimpanzee_wa",
     "dx": -4,
     "label": "chimpanzee (wa)",
     "name": "Chimpanzee (WA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b16",
  "group": "P19 HIS PICKS",
  "title": "CRAB",
  "look": "LEFT to RIGHT: CRAB BLUE (ANF), CRAB EMERALD (ANF), CRAB KING (ANF), CRAB SPIDER (ANF), CRAB STONE (ANF).",
  "rig": {
   "mob": "pw:crab_king_anf",
   "label": "crab king (anf)",
   "name": "Crab King (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:crab_blue_anf",
     "dx": -8,
     "label": "crab blue (anf)",
     "name": "Crab Blue (AnF)"
    },
    {
     "mob": "pw:crab_emerald_anf",
     "dx": -4,
     "label": "crab emerald (anf)",
     "name": "Crab Emerald (AnF)"
    },
    {
     "mob": "pw:crab_spider_anf",
     "dx": 4,
     "label": "crab spider (anf)",
     "name": "Crab Spider (AnF)"
    },
    {
     "mob": "pw:crab_stone_anf",
     "dx": 8,
     "label": "crab stone (anf)",
     "name": "Crab Stone (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b17",
  "group": "P19 HIS PICKS",
  "title": "CRAB",
  "look": "LEFT to RIGHT: CRAB (WA).",
  "rig": {
   "mob": "pw:crab_wa",
   "label": "crab (wa)",
   "name": "Crab (WA)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b18",
  "group": "P19 HIS PICKS",
  "title": "CRICKET",
  "look": "LEFT to RIGHT: CRICKET CAVE (ANF), CRICKET GREENBUSH (ANF), CRICKET HOUSE (ANF), CRICKET TOBACCO (ANF).",
  "rig": {
   "mob": "pw:cricket_house_anf",
   "label": "cricket house (anf)",
   "name": "Cricket House (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:cricket_cave_anf",
     "dx": -8,
     "label": "cricket cave (anf)",
     "name": "Cricket Cave (AnF)"
    },
    {
     "mob": "pw:cricket_greenbush_anf",
     "dx": -4,
     "label": "cricket greenbush (anf)",
     "name": "Cricket Greenbush (AnF)"
    },
    {
     "mob": "pw:cricket_tobacco_anf",
     "dx": 4,
     "label": "cricket tobacco (anf)",
     "name": "Cricket Tobacco (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b19",
  "group": "P19 HIS PICKS",
  "title": "CROCODILE",
  "look": "LEFT to RIGHT: CROC AFRICAN (ANF), CROC NILE (ANF), CROC SALTWATER (ANF).",
  "rig": {
   "mob": "pw:croc_nile_anf",
   "label": "croc nile (anf)",
   "name": "Croc Nile (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 7,
   "row": [
    {
     "mob": "pw:croc_african_anf",
     "dx": -7,
     "label": "croc african (anf)",
     "name": "Croc African (AnF)"
    },
    {
     "mob": "pw:croc_saltwater_anf",
     "dx": 7,
     "label": "croc saltwater (anf)",
     "name": "Croc Saltwater (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b20",
  "group": "P19 HIS PICKS",
  "title": "CROCODILE",
  "look": "LEFT to RIGHT: CROCODILE (WA), CROCODILE (YSAV).",
  "rig": {
   "mob": "pw:crocodile_ysav",
   "label": "crocodile (ysav)",
   "name": "Crocodile (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 7,
   "row": [
    {
     "mob": "pw:crocodile_wa",
     "dx": -7,
     "label": "crocodile (wa)",
     "name": "Crocodile (WA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b21",
  "group": "P19 HIS PICKS",
  "title": "CROW",
  "look": "LEFT to RIGHT: CROW CARRION (ANF), CROW COLLARED (ANF), CROW HOODED (ANF), CROW PIPING (ANF).",
  "rig": {
   "mob": "pw:crow_hooded_anf",
   "label": "crow hooded (anf)",
   "name": "Crow Hooded (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:crow_carrion_anf",
     "dx": -8,
     "label": "crow carrion (anf)",
     "name": "Crow Carrion (AnF)"
    },
    {
     "mob": "pw:crow_collared_anf",
     "dx": -4,
     "label": "crow collared (anf)",
     "name": "Crow Collared (AnF)"
    },
    {
     "mob": "pw:crow_piping_anf",
     "dx": 4,
     "label": "crow piping (anf)",
     "name": "Crow Piping (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b22",
  "group": "P19 HIS PICKS",
  "title": "DEER",
  "look": "LEFT to RIGHT: DEER FALLOW (ANF), DEER RED (ANF), DEER REINDEER (ANF), DEER ROE (ANF), DEER (WA).",
  "rig": {
   "mob": "pw:deer_reindeer_anf",
   "label": "deer reindeer (anf)",
   "name": "Deer Reindeer (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:deer_fallow_anf",
     "dx": -8,
     "label": "deer fallow (anf)",
     "name": "Deer Fallow (AnF)"
    },
    {
     "mob": "pw:deer_red_anf",
     "dx": -4,
     "label": "deer red (anf)",
     "name": "Deer Red (AnF)"
    },
    {
     "mob": "pw:deer_roe_anf",
     "dx": 4,
     "label": "deer roe (anf)",
     "name": "Deer Roe (AnF)"
    },
    {
     "mob": "pw:deer_wa",
     "dx": 8,
     "label": "deer (wa)",
     "name": "Deer (WA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b23",
  "group": "P19 HIS PICKS",
  "title": "DESERT OWL \u00b7 DOVE",
  "look": "LEFT to RIGHT: DESERT OWL (WS), DOVE (WA).",
  "rig": {
   "mob": "pw:dove_wa",
   "label": "dove (wa)",
   "name": "Dove (WA)",
   "half": 10,
   "halfz": 3,
   "height": 6,
   "row": [
    {
     "mob": "pw:desert_owl_ws",
     "dx": -4,
     "label": "desert owl (ws)",
     "name": "Desert Owl (WS)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b24",
  "group": "P19 HIS PICKS",
  "title": "DUCK",
  "look": "LEFT to RIGHT: DUCK BALI (ANF), DUCK GOLDENCASCADE (ANF), DUCK INDIANRUNNER (ANF), DUCK KINGEIDER (ANF), DUCK MADAGASCAR (ANF).",
  "rig": {
   "mob": "pw:duck_indianrunner_anf",
   "label": "duck indianrunner (anf)",
   "name": "Duck Indianrunner (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:duck_bali_anf",
     "dx": -8,
     "label": "duck bali (anf)",
     "name": "Duck Bali (AnF)"
    },
    {
     "mob": "pw:duck_goldencascade_anf",
     "dx": -4,
     "label": "duck goldencascade (anf)",
     "name": "Duck Goldencascade (AnF)"
    },
    {
     "mob": "pw:duck_kingeider_anf",
     "dx": 4,
     "label": "duck kingeider (anf)",
     "name": "Duck Kingeider (AnF)"
    },
    {
     "mob": "pw:duck_madagascar_anf",
     "dx": 8,
     "label": "duck madagascar (anf)",
     "name": "Duck Madagascar (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b25",
  "group": "P19 HIS PICKS",
  "title": "DUCK",
  "look": "LEFT to RIGHT: DUCK MALLARD (ANF), DUCK MANDARIN (ANF), DUCK PEKIN (ANF), DUCK EGG (WA), DUCK (WA).",
  "rig": {
   "mob": "pw:duck_pekin_anf",
   "label": "duck pekin (anf)",
   "name": "Duck Pekin (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:duck_mallard_anf",
     "dx": -8,
     "label": "duck mallard (anf)",
     "name": "Duck Mallard (AnF)"
    },
    {
     "mob": "pw:duck_mandarin_anf",
     "dx": -4,
     "label": "duck mandarin (anf)",
     "name": "Duck Mandarin (AnF)"
    },
    {
     "mob": "pw:duck_egg_wa",
     "dx": 4,
     "label": "duck egg (wa)",
     "name": "Duck Egg (WA)"
    },
    {
     "mob": "pw:duck_wa",
     "dx": 8,
     "label": "duck (wa)",
     "name": "Duck (WA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b26",
  "group": "P19 HIS PICKS",
  "title": "EAGLE",
  "look": "LEFT to RIGHT: EAGLE BALD (ANF), EAGLE BLACKHAWK (ANF), EAGLE CROWNED (ANF), EAGLE GOLDEN (ANF), EAGLE SEA (ANF).",
  "rig": {
   "mob": "pw:eagle_crowned_anf",
   "label": "eagle crowned (anf)",
   "name": "Eagle Crowned (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:eagle_bald_anf",
     "dx": -8,
     "label": "eagle bald (anf)",
     "name": "Eagle Bald (AnF)"
    },
    {
     "mob": "pw:eagle_blackhawk_anf",
     "dx": -4,
     "label": "eagle blackhawk (anf)",
     "name": "Eagle Blackhawk (AnF)"
    },
    {
     "mob": "pw:eagle_golden_anf",
     "dx": 4,
     "label": "eagle golden (anf)",
     "name": "Eagle Golden (AnF)"
    },
    {
     "mob": "pw:eagle_sea_anf",
     "dx": 8,
     "label": "eagle sea (anf)",
     "name": "Eagle Sea (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b27",
  "group": "P19 HIS PICKS",
  "title": "EAGLE",
  "look": "LEFT to RIGHT: EAGLE WHITETAILED (ANF), EAGLE (WA), AFRICAN BLACK EAGLE (YSAV), BABY AFRICAN BLACK EAGLE (YSAV), BABY FISHER EAGLE (YSAV).",
  "rig": {
   "mob": "pw:african_black_eagle_ysav",
   "label": "african black eagle (ysav)",
   "name": "African Black Eagle (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 6,
   "row": [
    {
     "mob": "pw:eagle_whitetailed_anf",
     "dx": -8,
     "label": "eagle whitetailed (anf)",
     "name": "Eagle Whitetailed (AnF)"
    },
    {
     "mob": "pw:eagle_wa",
     "dx": -4,
     "label": "eagle (wa)",
     "name": "Eagle (WA)"
    },
    {
     "mob": "pw:baby_african_black_eagle_ysav",
     "dx": 4,
     "label": "baby african black eagle (ysav)",
     "name": "Baby African Black Eagle (YSav)"
    },
    {
     "mob": "pw:baby_fisher_eagle_ysav",
     "dx": 8,
     "label": "baby fisher eagle (ysav)",
     "name": "Baby Fisher Eagle (YSav)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b28",
  "group": "P19 HIS PICKS",
  "title": "EAGLE",
  "look": "LEFT to RIGHT: FISHER EAGLE (YSAV).",
  "rig": {
   "mob": "pw:fisher_eagle_ysav",
   "label": "fisher eagle (ysav)",
   "name": "Fisher Eagle (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 6,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b29",
  "group": "P19 HIS PICKS",
  "title": "ELEPHANT",
  "look": "LEFT to RIGHT: ELEPHANT AFRICAN (ANF), ELEPHANT ASIAN (ANF), AFRICAN ELEPHANT (WA).",
  "rig": {
   "mob": "pw:elephant_asian_anf",
   "label": "elephant asian (anf)",
   "name": "Elephant Asian (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 7,
   "row": [
    {
     "mob": "pw:elephant_african_anf",
     "dx": -7,
     "label": "elephant african (anf)",
     "name": "Elephant African (AnF)"
    },
    {
     "mob": "pw:african_elephant_wa",
     "dx": 7,
     "label": "african elephant (wa)",
     "name": "African Elephant (WA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b30",
  "group": "P19 HIS PICKS",
  "title": "ELEPHANT",
  "look": "LEFT to RIGHT: ASIAN ELEPHANT (WA), ELEPHANT (YSAV).",
  "rig": {
   "mob": "pw:elephant_ysav",
   "label": "elephant (ysav)",
   "name": "Elephant (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 7,
   "row": [
    {
     "mob": "pw:asian_elephant_wa",
     "dx": -7,
     "label": "asian elephant (wa)",
     "name": "Asian Elephant (WA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b31",
  "group": "P19 HIS PICKS",
  "title": "EMU \u00b7 FERRET \u00b7 FIREFLY",
  "look": "LEFT to RIGHT: EMU (YTRI), FERRET COMMON (ANF), FIREFLY (ANF).",
  "rig": {
   "mob": "pw:ferret_common_anf",
   "label": "ferret common (anf)",
   "name": "Ferret Common (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:emu_ytri",
     "dx": -4,
     "label": "emu (ytri)",
     "name": "Emu (YTri)"
    },
    {
     "mob": "pw:firefly_anf",
     "dx": 4,
     "label": "firefly (anf)",
     "name": "Firefly (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b32",
  "group": "P19 HIS PICKS",
  "title": "FLAMINGO",
  "look": "LEFT to RIGHT: FLAMINGO AMERICAN (ANF), FLAMINGO ANDEAN (ANF), FLAMINGO GREATER (ANF), FLAMINGO JAMES (ANF).",
  "rig": {
   "mob": "pw:flamingo_greater_anf",
   "label": "flamingo greater (anf)",
   "name": "Flamingo Greater (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:flamingo_american_anf",
     "dx": -8,
     "label": "flamingo american (anf)",
     "name": "Flamingo American (AnF)"
    },
    {
     "mob": "pw:flamingo_andean_anf",
     "dx": -4,
     "label": "flamingo andean (anf)",
     "name": "Flamingo Andean (AnF)"
    },
    {
     "mob": "pw:flamingo_james_anf",
     "dx": 4,
     "label": "flamingo james (anf)",
     "name": "Flamingo James (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b33",
  "group": "P19 HIS PICKS",
  "title": "GAZELLE \u00b7 GELADA \u00b7 GILA MONSTER",
  "look": "LEFT to RIGHT: GAZELLE FEMALE (YSAV), GAZELLE (YSAV), GELADA (WS), GILA MONSTER (WS).",
  "rig": {
   "mob": "pw:gelada_ws",
   "label": "gelada (ws)",
   "name": "Gelada (WS)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:gazelle_female_ysav",
     "dx": -8,
     "label": "gazelle female (ysav)",
     "name": "Gazelle Female (YSav)"
    },
    {
     "mob": "pw:gazelle_ysav",
     "dx": -4,
     "label": "gazelle (ysav)",
     "name": "Gazelle (YSav)"
    },
    {
     "mob": "pw:gila_monster_ws",
     "dx": 4,
     "label": "gila monster (ws)",
     "name": "Gila Monster (WS)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b34",
  "group": "P19 HIS PICKS",
  "title": "GIRAFFE",
  "look": "LEFT to RIGHT: GIRAFFE MASAI (ANF), GIRAFFE NUBIAN (ANF), GIRAFFE RETICULATED (ANF), GIRAFFE SOUTHAFRICAN (ANF), GIRAFFE (WA).",
  "rig": {
   "mob": "pw:giraffe_reticulated_anf",
   "label": "giraffe reticulated (anf)",
   "name": "Giraffe Reticulated (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:giraffe_masai_anf",
     "dx": -8,
     "label": "giraffe masai (anf)",
     "name": "Giraffe Masai (AnF)"
    },
    {
     "mob": "pw:giraffe_nubian_anf",
     "dx": -4,
     "label": "giraffe nubian (anf)",
     "name": "Giraffe Nubian (AnF)"
    },
    {
     "mob": "pw:giraffe_southafrican_anf",
     "dx": 4,
     "label": "giraffe southafrican (anf)",
     "name": "Giraffe Southafrican (AnF)"
    },
    {
     "mob": "pw:giraffe_wa",
     "dx": 8,
     "label": "giraffe (wa)",
     "name": "Giraffe (WA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b35",
  "group": "P19 HIS PICKS",
  "title": "GIRAFFE",
  "look": "LEFT to RIGHT: GIRAFFE (YSAV).",
  "rig": {
   "mob": "pw:giraffe_ysav",
   "label": "giraffe (ysav)",
   "name": "Giraffe (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b36",
  "group": "P19 HIS PICKS",
  "title": "GNU",
  "look": "LEFT to RIGHT: GNU (YSAV).",
  "rig": {
   "mob": "pw:gnu_ysav",
   "label": "gnu (ysav)",
   "name": "Gnu (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b37",
  "group": "P19 HIS PICKS",
  "title": "GOOSE",
  "look": "LEFT to RIGHT: GOOSE BARNACLE (ANF), GOOSE CANADA (ANF), GOOSE EGYPTIAN (ANF), GOOSE MAGELLAN (ANF), GOOSE ROMAN (ANF).",
  "rig": {
   "mob": "pw:goose_egyptian_anf",
   "label": "goose egyptian (anf)",
   "name": "Goose Egyptian (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:goose_barnacle_anf",
     "dx": -8,
     "label": "goose barnacle (anf)",
     "name": "Goose Barnacle (AnF)"
    },
    {
     "mob": "pw:goose_canada_anf",
     "dx": -4,
     "label": "goose canada (anf)",
     "name": "Goose Canada (AnF)"
    },
    {
     "mob": "pw:goose_magellan_anf",
     "dx": 4,
     "label": "goose magellan (anf)",
     "name": "Goose Magellan (AnF)"
    },
    {
     "mob": "pw:goose_roman_anf",
     "dx": 8,
     "label": "goose roman (anf)",
     "name": "Goose Roman (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b38",
  "group": "P19 HIS PICKS",
  "title": "GORILLA",
  "look": "LEFT to RIGHT: GORILLA (WA), GORILLA (YTRI), GORILLA (OURS). World Animals and yCreatures gorillas next to ours (OURS).",
  "rig": {
   "mob": "pw:gorilla_ytri",
   "label": "gorilla (ytri)",
   "name": "Gorilla (YTri)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:gorilla_wa",
     "dx": -4,
     "label": "gorilla (wa)",
     "name": "Gorilla (WA)"
    },
    {
     "mob": "sf_nba:gorilla",
     "dx": 4,
     "label": "gorilla (ours)",
     "name": "Gorilla (OURS)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b39",
  "group": "P19 HIS PICKS",
  "title": "HAMSTER",
  "look": "LEFT to RIGHT: HAMSTER DWARF (ANF), HAMSTER SYRIAN (ANF).",
  "rig": {
   "mob": "pw:hamster_syrian_anf",
   "label": "hamster syrian (anf)",
   "name": "Hamster Syrian (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:hamster_dwarf_anf",
     "dx": -4,
     "label": "hamster dwarf (anf)",
     "name": "Hamster Dwarf (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b40",
  "group": "P19 HIS PICKS",
  "title": "HEDGEHOG",
  "look": "LEFT to RIGHT: HEDGEHOG DESERT (ANF), HEDGEHOG EURO (ANF), HEDGEHOG LONGEARED (ANF), HEDGEHOG MADRAS (ANF), HEDGEHOG SOUTHAFRICAN (ANF).",
  "rig": {
   "mob": "pw:hedgehog_longeared_anf",
   "label": "hedgehog longeared (anf)",
   "name": "Hedgehog Longeared (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:hedgehog_desert_anf",
     "dx": -8,
     "label": "hedgehog desert (anf)",
     "name": "Hedgehog Desert (AnF)"
    },
    {
     "mob": "pw:hedgehog_euro_anf",
     "dx": -4,
     "label": "hedgehog euro (anf)",
     "name": "Hedgehog Euro (AnF)"
    },
    {
     "mob": "pw:hedgehog_madras_anf",
     "dx": 4,
     "label": "hedgehog madras (anf)",
     "name": "Hedgehog Madras (AnF)"
    },
    {
     "mob": "pw:hedgehog_southafrican_anf",
     "dx": 8,
     "label": "hedgehog southafrican (anf)",
     "name": "Hedgehog Southafrican (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b41",
  "group": "P19 HIS PICKS",
  "title": "HEDGEHOG",
  "look": "LEFT to RIGHT: HEDGEHOG (WA).",
  "rig": {
   "mob": "pw:hedgehog_wa",
   "label": "hedgehog (wa)",
   "name": "Hedgehog (WA)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b42",
  "group": "P19 HIS PICKS",
  "title": "HORNBILL \u00b7 HUMMINGBIRD \u00b7 HYENA",
  "look": "LEFT to RIGHT: HORNBILL (WS), HUMMINGBIRD (YTRI), HYENA (ANF), HYENAS (WA), HYENA (YSAV).",
  "rig": {
   "mob": "pw:hyena_anf",
   "label": "hyena (anf)",
   "name": "Hyena (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 6,
   "row": [
    {
     "mob": "pw:hornbill_ws",
     "dx": -8,
     "label": "hornbill (ws)",
     "name": "Hornbill (WS)"
    },
    {
     "mob": "pw:hummingbird_ytri",
     "dx": -4,
     "label": "hummingbird (ytri)",
     "name": "Hummingbird (YTri)"
    },
    {
     "mob": "pw:hyenas_wa",
     "dx": 4,
     "label": "hyenas (wa)",
     "name": "Hyenas (WA)"
    },
    {
     "mob": "pw:hyena_ysav",
     "dx": 8,
     "label": "hyena (ysav)",
     "name": "Hyena (YSav)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b43",
  "group": "P19 HIS PICKS",
  "title": "IGUANA \u00b7 KAKAPO \u00b7 KOMODO DRAGON",
  "look": "LEFT to RIGHT: IGUANA (ANF), KAKAPO (WWA), KOMODO DRAGON (WA), KOMODO DRAGON (YTRI).",
  "rig": {
   "mob": "pw:komodo_dragon_wa",
   "label": "komodo dragon (wa)",
   "name": "Komodo Dragon (WA)",
   "half": 10,
   "halfz": 3,
   "height": 6,
   "row": [
    {
     "mob": "pw:iguana_anf",
     "dx": -8,
     "label": "iguana (anf)",
     "name": "Iguana (AnF)"
    },
    {
     "mob": "pw:kakapo_wwa",
     "dx": -4,
     "label": "kakapo (wwa)",
     "name": "Kakapo (WWA)"
    },
    {
     "mob": "pw:komodo_dragon_ytri",
     "dx": 4,
     "label": "komodo dragon (ytri)",
     "name": "Komodo Dragon (YTri)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b44",
  "group": "P19 HIS PICKS",
  "title": "LADYBUG",
  "look": "LEFT to RIGHT: LADYBUG 15SPOTTED (ANF), LADYBUG 22SPOTTED (ANF), LADYBUG 7SPOTTED (ANF), LADYBUG 9SPOTTED (ANF), LADYBUG HARLEQUIN (ANF).",
  "rig": {
   "mob": "pw:ladybug_7spotted_anf",
   "label": "ladybug 7spotted (anf)",
   "name": "Ladybug 7Spotted (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:ladybug_15spotted_anf",
     "dx": -8,
     "label": "ladybug 15spotted (anf)",
     "name": "Ladybug 15Spotted (AnF)"
    },
    {
     "mob": "pw:ladybug_22spotted_anf",
     "dx": -4,
     "label": "ladybug 22spotted (anf)",
     "name": "Ladybug 22Spotted (AnF)"
    },
    {
     "mob": "pw:ladybug_9spotted_anf",
     "dx": 4,
     "label": "ladybug 9spotted (anf)",
     "name": "Ladybug 9Spotted (AnF)"
    },
    {
     "mob": "pw:ladybug_harlequin_anf",
     "dx": 8,
     "label": "ladybug harlequin (anf)",
     "name": "Ladybug Harlequin (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b45",
  "group": "P19 HIS PICKS",
  "title": "LEMUR",
  "look": "LEFT to RIGHT: LEMUR GOLDENBAMBOO (ANF), LEMUR MOUSE BROWN (ANF), LEMUR MOUSE GREY (ANF), LEMUR REDRUFFED (ANF), LEMUR RINGTAILED (ANF).",
  "rig": {
   "mob": "pw:lemur_mouse_grey_anf",
   "label": "lemur mouse grey (anf)",
   "name": "Lemur Mouse Grey (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:lemur_goldenbamboo_anf",
     "dx": -8,
     "label": "lemur goldenbamboo (anf)",
     "name": "Lemur Goldenbamboo (AnF)"
    },
    {
     "mob": "pw:lemur_mouse_brown_anf",
     "dx": -4,
     "label": "lemur mouse brown (anf)",
     "name": "Lemur Mouse Brown (AnF)"
    },
    {
     "mob": "pw:lemur_redruffed_anf",
     "dx": 4,
     "label": "lemur redruffed (anf)",
     "name": "Lemur Redruffed (AnF)"
    },
    {
     "mob": "pw:lemur_ringtailed_anf",
     "dx": 8,
     "label": "lemur ringtailed (anf)",
     "name": "Lemur Ringtailed (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b46",
  "group": "P19 HIS PICKS",
  "title": "LEMUR",
  "look": "LEFT to RIGHT: LEMUR SPORTIVE (ANF), LEMUR (YTRI).",
  "rig": {
   "mob": "pw:lemur_ytri",
   "label": "lemur (ytri)",
   "name": "Lemur (YTri)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:lemur_sportive_anf",
     "dx": -4,
     "label": "lemur sportive (anf)",
     "name": "Lemur Sportive (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b47",
  "group": "P19 HIS PICKS",
  "title": "LEOPARD",
  "look": "LEFT to RIGHT: LEOPARD CLOUDED (ANF), LEOPARD JUNGLE (ANF), LEOPARD PANTHER (ANF), LEOPARD SNOW (ANF), LEOPARD (YSAV).",
  "rig": {
   "mob": "pw:leopard_panther_anf",
   "label": "leopard panther (anf)",
   "name": "Leopard Panther (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:leopard_clouded_anf",
     "dx": -8,
     "label": "leopard clouded (anf)",
     "name": "Leopard Clouded (AnF)"
    },
    {
     "mob": "pw:leopard_jungle_anf",
     "dx": -4,
     "label": "leopard jungle (anf)",
     "name": "Leopard Jungle (AnF)"
    },
    {
     "mob": "pw:leopard_snow_anf",
     "dx": 4,
     "label": "leopard snow (anf)",
     "name": "Leopard Snow (AnF)"
    },
    {
     "mob": "pw:leopard_ysav",
     "dx": 8,
     "label": "leopard (ysav)",
     "name": "Leopard (YSav)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b48",
  "group": "P19 HIS PICKS",
  "title": "LION",
  "look": "LEFT to RIGHT: LION AFRICAN (ANF), LION ASIATIC (ANF), LION TRANSVAAL (ANF), LIONESS AFRICAN (ANF), LIONESS ASIATIC (ANF).",
  "rig": {
   "mob": "pw:lion_transvaal_anf",
   "label": "lion transvaal (anf)",
   "name": "Lion Transvaal (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:lion_african_anf",
     "dx": -8,
     "label": "lion african (anf)",
     "name": "Lion African (AnF)"
    },
    {
     "mob": "pw:lion_asiatic_anf",
     "dx": -4,
     "label": "lion asiatic (anf)",
     "name": "Lion Asiatic (AnF)"
    },
    {
     "mob": "pw:lioness_african_anf",
     "dx": 4,
     "label": "lioness african (anf)",
     "name": "Lioness African (AnF)"
    },
    {
     "mob": "pw:lioness_asiatic_anf",
     "dx": 8,
     "label": "lioness asiatic (anf)",
     "name": "Lioness Asiatic (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b49",
  "group": "P19 HIS PICKS",
  "title": "LION",
  "look": "LEFT to RIGHT: LIONESS TRANSVAAL (ANF), LION (WA), BABY LION (YSAV), LION (YSAV), LIONESS (YSAV).",
  "rig": {
   "mob": "pw:baby_lion_ysav",
   "label": "baby lion (ysav)",
   "name": "Baby Lion (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:lioness_transvaal_anf",
     "dx": -8,
     "label": "lioness transvaal (anf)",
     "name": "Lioness Transvaal (AnF)"
    },
    {
     "mob": "pw:lion_wa",
     "dx": -4,
     "label": "lion (wa)",
     "name": "Lion (WA)"
    },
    {
     "mob": "pw:lion_ysav",
     "dx": 4,
     "label": "lion (ysav)",
     "name": "Lion (YSav)"
    },
    {
     "mob": "pw:lioness_ysav",
     "dx": 8,
     "label": "lioness (ysav)",
     "name": "Lioness (YSav)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b50",
  "group": "P19 HIS PICKS",
  "title": "LION",
  "look": "LEFT to RIGHT: WHITE LION (YSAV), WHITE LIONESS (YSAV).",
  "rig": {
   "mob": "pw:white_lioness_ysav",
   "label": "white lioness (ysav)",
   "name": "White Lioness (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:white_lion_ysav",
     "dx": -4,
     "label": "white lion (ysav)",
     "name": "White Lion (YSav)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b51",
  "group": "P19 HIS PICKS",
  "title": "LYNX \u00b7 MEERKAT \u00b7 MOLE \u00b7 MONKEY",
  "look": "LEFT to RIGHT: LYNX (WS), MEERKAT (ANF), MEERKAT (YTRI), MOLE (YTRI), MONKEY (WS).",
  "rig": {
   "mob": "pw:meerkat_ytri",
   "label": "meerkat (ytri)",
   "name": "Meerkat (YTri)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:lynx_ws",
     "dx": -8,
     "label": "lynx (ws)",
     "name": "Lynx (WS)"
    },
    {
     "mob": "pw:meerkat_anf",
     "dx": -4,
     "label": "meerkat (anf)",
     "name": "Meerkat (AnF)"
    },
    {
     "mob": "pw:mole_ytri",
     "dx": 4,
     "label": "mole (ytri)",
     "name": "Mole (YTri)"
    },
    {
     "mob": "pw:monkey_ws",
     "dx": 8,
     "label": "monkey (ws)",
     "name": "Monkey (WS)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b52",
  "group": "P19 HIS PICKS",
  "title": "MOOSE \u00b7 ORANGUTAN",
  "look": "LEFT to RIGHT: MOOSE ALASKAN (ANF), MOOSE CANADIAN (ANF), ORANGUTAN (ANF).",
  "rig": {
   "mob": "pw:moose_canadian_anf",
   "label": "moose canadian (anf)",
   "name": "Moose Canadian (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:moose_alaskan_anf",
     "dx": -4,
     "label": "moose alaskan (anf)",
     "name": "Moose Alaskan (AnF)"
    },
    {
     "mob": "pw:orangutan_anf",
     "dx": 4,
     "label": "orangutan (anf)",
     "name": "Orangutan (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b53",
  "group": "P19 HIS PICKS",
  "title": "OSTRICH",
  "look": "LEFT to RIGHT: OSTRICH (ANF), OSTRICH EGG (WA), OSTRICH (WA), OSTRICH (WS), OSTRICH (YSAV).",
  "rig": {
   "mob": "pw:ostrich_wa",
   "label": "ostrich (wa)",
   "name": "Ostrich (WA)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:ostrich_anf",
     "dx": -8,
     "label": "ostrich (anf)",
     "name": "Ostrich (AnF)"
    },
    {
     "mob": "pw:ostrich_egg_wa",
     "dx": -4,
     "label": "ostrich egg (wa)",
     "name": "Ostrich Egg (WA)"
    },
    {
     "mob": "pw:ostrich_ws",
     "dx": 4,
     "label": "ostrich (ws)",
     "name": "Ostrich (WS)"
    },
    {
     "mob": "pw:ostrich_ysav",
     "dx": 8,
     "label": "ostrich (ysav)",
     "name": "Ostrich (YSav)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b54",
  "group": "P19 HIS PICKS",
  "title": "OTTER",
  "look": "LEFT to RIGHT: OTTER (YTRI).",
  "rig": {
   "mob": "pw:otter_ytri",
   "label": "otter (ytri)",
   "name": "Otter (YTri)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b55",
  "group": "P19 HIS PICKS",
  "title": "OWL",
  "look": "LEFT to RIGHT: OWL BARN (ANF), OWL SNOWY (ANF), OWL TAWNY (ANF), BARN OWL (YTRI), OWL (YTRI).",
  "rig": {
   "mob": "pw:owl_tawny_anf",
   "label": "owl tawny (anf)",
   "name": "Owl Tawny (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 6,
   "row": [
    {
     "mob": "pw:owl_barn_anf",
     "dx": -8,
     "label": "owl barn (anf)",
     "name": "Owl Barn (AnF)"
    },
    {
     "mob": "pw:owl_snowy_anf",
     "dx": -4,
     "label": "owl snowy (anf)",
     "name": "Owl Snowy (AnF)"
    },
    {
     "mob": "pw:barn_owl_ytri",
     "dx": 4,
     "label": "barn owl (ytri)",
     "name": "Barn Owl (YTri)"
    },
    {
     "mob": "pw:owl_ytri",
     "dx": 8,
     "label": "owl (ytri)",
     "name": "Owl (YTri)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b56",
  "group": "P19 HIS PICKS",
  "title": "PELICAN \u00b7 PLATYPUS",
  "look": "LEFT to RIGHT: PELICAN AMERICANWHITE (ANF), PELICAN AUSTRALIAN (ANF), PELICAN BROWN (ANF), PELICAN GREATWHITE (ANF), PLATYPUS (YTRI).",
  "rig": {
   "mob": "pw:pelican_brown_anf",
   "label": "pelican brown (anf)",
   "name": "Pelican Brown (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:pelican_americanwhite_anf",
     "dx": -8,
     "label": "pelican americanwhite (anf)",
     "name": "Pelican Americanwhite (AnF)"
    },
    {
     "mob": "pw:pelican_australian_anf",
     "dx": -4,
     "label": "pelican australian (anf)",
     "name": "Pelican Australian (AnF)"
    },
    {
     "mob": "pw:pelican_greatwhite_anf",
     "dx": 4,
     "label": "pelican greatwhite (anf)",
     "name": "Pelican Greatwhite (AnF)"
    },
    {
     "mob": "pw:platypus_ytri",
     "dx": 8,
     "label": "platypus (ytri)",
     "name": "Platypus (YTri)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b57",
  "group": "P19 HIS PICKS",
  "title": "RACCOON",
  "look": "LEFT to RIGHT: RACCOON (ANF), RACCOON (WWA).",
  "rig": {
   "mob": "pw:raccoon_wwa",
   "label": "raccoon (wwa)",
   "name": "Raccoon (WWA)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:raccoon_anf",
     "dx": -4,
     "label": "raccoon (anf)",
     "name": "Raccoon (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b58",
  "group": "P19 HIS PICKS",
  "title": "RAT",
  "look": "LEFT to RIGHT: RAT BLACK (ANF), RAT BROWN (ANF), RAT FANCY (ANF), RAT MARSH (ANF), RAT PACK (ANF).",
  "rig": {
   "mob": "pw:rat_fancy_anf",
   "label": "rat fancy (anf)",
   "name": "Rat Fancy (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:rat_black_anf",
     "dx": -8,
     "label": "rat black (anf)",
     "name": "Rat Black (AnF)"
    },
    {
     "mob": "pw:rat_brown_anf",
     "dx": -4,
     "label": "rat brown (anf)",
     "name": "Rat Brown (AnF)"
    },
    {
     "mob": "pw:rat_marsh_anf",
     "dx": 4,
     "label": "rat marsh (anf)",
     "name": "Rat Marsh (AnF)"
    },
    {
     "mob": "pw:rat_pack_anf",
     "dx": 8,
     "label": "rat pack (anf)",
     "name": "Rat Pack (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b59",
  "group": "P19 HIS PICKS",
  "title": "RAT",
  "look": "LEFT to RIGHT: RAT (WA).",
  "rig": {
   "mob": "pw:rat_wa",
   "label": "rat (wa)",
   "name": "Rat (WA)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b60",
  "group": "P19 HIS PICKS",
  "title": "RATTLESNAKE \u00b7 RAVEN \u00b7 RED PANDA",
  "look": "LEFT to RIGHT: RATTLESNAKE (WS), RAVEN COMMON (ANF), RAVEN WHITENECKED (ANF), RED PANDA (WA), RED PANDA (WWA).",
  "rig": {
   "mob": "pw:raven_whitenecked_anf",
   "label": "raven whitenecked (anf)",
   "name": "Raven Whitenecked (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:rattlesnake_ws",
     "dx": -8,
     "label": "rattlesnake (ws)",
     "name": "Rattlesnake (WS)"
    },
    {
     "mob": "pw:raven_common_anf",
     "dx": -4,
     "label": "raven common (anf)",
     "name": "Raven Common (AnF)"
    },
    {
     "mob": "pw:red_panda_wa",
     "dx": 4,
     "label": "red panda (wa)",
     "name": "Red Panda (WA)"
    },
    {
     "mob": "pw:red_panda_wwa",
     "dx": 8,
     "label": "red panda (wwa)",
     "name": "Red Panda (WWA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b61",
  "group": "P19 HIS PICKS",
  "title": "RHINO",
  "look": "LEFT to RIGHT: RHINO BLACK (ANF), RHINO INDIAN (ANF), RHINO SUMATRAN (ANF), RHINO WHITE (ANF), RHINO (WA).",
  "rig": {
   "mob": "pw:rhino_sumatran_anf",
   "label": "rhino sumatran (anf)",
   "name": "Rhino Sumatran (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:rhino_black_anf",
     "dx": -8,
     "label": "rhino black (anf)",
     "name": "Rhino Black (AnF)"
    },
    {
     "mob": "pw:rhino_indian_anf",
     "dx": -4,
     "label": "rhino indian (anf)",
     "name": "Rhino Indian (AnF)"
    },
    {
     "mob": "pw:rhino_white_anf",
     "dx": 4,
     "label": "rhino white (anf)",
     "name": "Rhino White (AnF)"
    },
    {
     "mob": "pw:rhino_wa",
     "dx": 8,
     "label": "rhino (wa)",
     "name": "Rhino (WA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b62",
  "group": "P19 HIS PICKS",
  "title": "RHINO",
  "look": "LEFT to RIGHT: RHINO (YSAV).",
  "rig": {
   "mob": "pw:rhino_ysav",
   "label": "rhino (ysav)",
   "name": "Rhino (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b63",
  "group": "P19 HIS PICKS",
  "title": "ROBIN \u00b7 SCORPION",
  "look": "LEFT to RIGHT: ROBIN (ANF), SCORPION DEATHSTALKER (ANF), SCORPION GIANTDESERT (ANF), SCORPION GIANTFOREST (ANF), SCORPION INDIANRED (ANF).",
  "rig": {
   "mob": "pw:scorpion_giantdesert_anf",
   "label": "scorpion giantdesert (anf)",
   "name": "Scorpion Giantdesert (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:robin_anf",
     "dx": -8,
     "label": "robin (anf)",
     "name": "Robin (AnF)"
    },
    {
     "mob": "pw:scorpion_deathstalker_anf",
     "dx": -4,
     "label": "scorpion deathstalker (anf)",
     "name": "Scorpion Deathstalker (AnF)"
    },
    {
     "mob": "pw:scorpion_giantforest_anf",
     "dx": 4,
     "label": "scorpion giantforest (anf)",
     "name": "Scorpion Giantforest (AnF)"
    },
    {
     "mob": "pw:scorpion_indianred_anf",
     "dx": 8,
     "label": "scorpion indianred (anf)",
     "name": "Scorpion Indianred (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b64",
  "group": "P19 HIS PICKS",
  "title": "SEAGULL",
  "look": "LEFT to RIGHT: GULL BLACKHEADED (ANF), GULL BONAPARTE (ANF), GULL COMMON (ANF), GULL GREATBLACKBACKED (ANF), GULL HERRING (ANF).",
  "rig": {
   "mob": "pw:gull_common_anf",
   "label": "gull common (anf)",
   "name": "Gull Common (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:gull_blackheaded_anf",
     "dx": -8,
     "label": "gull blackheaded (anf)",
     "name": "Gull Blackheaded (AnF)"
    },
    {
     "mob": "pw:gull_bonaparte_anf",
     "dx": -4,
     "label": "gull bonaparte (anf)",
     "name": "Gull Bonaparte (AnF)"
    },
    {
     "mob": "pw:gull_greatblackbacked_anf",
     "dx": 4,
     "label": "gull greatblackbacked (anf)",
     "name": "Gull Greatblackbacked (AnF)"
    },
    {
     "mob": "pw:gull_herring_anf",
     "dx": 8,
     "label": "gull herring (anf)",
     "name": "Gull Herring (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b65",
  "group": "P19 HIS PICKS",
  "title": "SEAGULL",
  "look": "LEFT to RIGHT: GULL KITTIWAKE (ANF), GULL LESSERBLACKBACKED (ANF).",
  "rig": {
   "mob": "pw:gull_lesserblackbacked_anf",
   "label": "gull lesserblackbacked (anf)",
   "name": "Gull Lesserblackbacked (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:gull_kittiwake_anf",
     "dx": -4,
     "label": "gull kittiwake (anf)",
     "name": "Gull Kittiwake (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b66",
  "group": "P19 HIS PICKS",
  "title": "SEAL",
  "look": "LEFT to RIGHT: SEAL COMMON (ANF), SEAL GREY (ANF), SEAL HARP (ANF), SEAL (WWA).",
  "rig": {
   "mob": "pw:seal_harp_anf",
   "label": "seal harp (anf)",
   "name": "Seal Harp (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:seal_common_anf",
     "dx": -8,
     "label": "seal common (anf)",
     "name": "Seal Common (AnF)"
    },
    {
     "mob": "pw:seal_grey_anf",
     "dx": -4,
     "label": "seal grey (anf)",
     "name": "Seal Grey (AnF)"
    },
    {
     "mob": "pw:seal_wwa",
     "dx": 4,
     "label": "seal (wwa)",
     "name": "Seal (WWA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b67",
  "group": "P19 HIS PICKS",
  "title": "SKUNK \u00b7 SLUG",
  "look": "LEFT to RIGHT: SKUNK (ANF), SKUNK (YTRI), SLUG EUROPEANRED (ANF), SLUG LEOPARD (ANF), SLUG SPANISH (ANF).",
  "rig": {
   "mob": "pw:slug_europeanred_anf",
   "label": "slug europeanred (anf)",
   "name": "Slug Europeanred (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:skunk_anf",
     "dx": -8,
     "label": "skunk (anf)",
     "name": "Skunk (AnF)"
    },
    {
     "mob": "pw:skunk_ytri",
     "dx": -4,
     "label": "skunk (ytri)",
     "name": "Skunk (YTri)"
    },
    {
     "mob": "pw:slug_leopard_anf",
     "dx": 4,
     "label": "slug leopard (anf)",
     "name": "Slug Leopard (AnF)"
    },
    {
     "mob": "pw:slug_spanish_anf",
     "dx": 8,
     "label": "slug spanish (anf)",
     "name": "Slug Spanish (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b68",
  "group": "P19 HIS PICKS",
  "title": "SNAIL",
  "look": "LEFT to RIGHT: SNAIL CANDYCANE (ANF), SNAIL DESERT (ANF), SNAIL GARDEN (ANF), SNAIL GIANTAFRICAN (ANF), SNAIL MILK (ANF).",
  "rig": {
   "mob": "pw:snail_garden_anf",
   "label": "snail garden (anf)",
   "name": "Snail Garden (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:snail_candycane_anf",
     "dx": -8,
     "label": "snail candycane (anf)",
     "name": "Snail Candycane (AnF)"
    },
    {
     "mob": "pw:snail_desert_anf",
     "dx": -4,
     "label": "snail desert (anf)",
     "name": "Snail Desert (AnF)"
    },
    {
     "mob": "pw:snail_giantafrican_anf",
     "dx": 4,
     "label": "snail giantafrican (anf)",
     "name": "Snail Giantafrican (AnF)"
    },
    {
     "mob": "pw:snail_milk_anf",
     "dx": 8,
     "label": "snail milk (anf)",
     "name": "Snail Milk (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b69",
  "group": "P19 HIS PICKS",
  "title": "SNAKE",
  "look": "LEFT to RIGHT: SNAKE ANACONDA GREEN (ANF), SNAKE ANACONDA YELLOW (ANF), SNAKE BOA KENYANSAND (ANF), SNAKE COBRA INDIAN (ANF), SNAKE COBRA KING (ANF).",
  "rig": {
   "mob": "pw:snake_boa_kenyansand_anf",
   "label": "snake boa kenyansand (anf)",
   "name": "Snake Boa Kenyansand (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:snake_anaconda_green_anf",
     "dx": -8,
     "label": "snake anaconda green (anf)",
     "name": "Snake Anaconda Green (AnF)"
    },
    {
     "mob": "pw:snake_anaconda_yellow_anf",
     "dx": -4,
     "label": "snake anaconda yellow (anf)",
     "name": "Snake Anaconda Yellow (AnF)"
    },
    {
     "mob": "pw:snake_cobra_indian_anf",
     "dx": 4,
     "label": "snake cobra indian (anf)",
     "name": "Snake Cobra Indian (AnF)"
    },
    {
     "mob": "pw:snake_cobra_king_anf",
     "dx": 8,
     "label": "snake cobra king (anf)",
     "name": "Snake Cobra King (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b70",
  "group": "P19 HIS PICKS",
  "title": "SNAKE",
  "look": "LEFT to RIGHT: SNAKE CORN (ANF), SNAKE GARTER BUTLER (ANF), SNAKE GARTER CALIFORNIA (ANF), SNAKE MAMBA BLACK (ANF), SNAKE MAMBA EASTERNGREEN (ANF).",
  "rig": {
   "mob": "pw:snake_garter_california_anf",
   "label": "snake garter california (anf)",
   "name": "Snake Garter California (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:snake_corn_anf",
     "dx": -8,
     "label": "snake corn (anf)",
     "name": "Snake Corn (AnF)"
    },
    {
     "mob": "pw:snake_garter_butler_anf",
     "dx": -4,
     "label": "snake garter butler (anf)",
     "name": "Snake Garter Butler (AnF)"
    },
    {
     "mob": "pw:snake_mamba_black_anf",
     "dx": 4,
     "label": "snake mamba black (anf)",
     "name": "Snake Mamba Black (AnF)"
    },
    {
     "mob": "pw:snake_mamba_easterngreen_anf",
     "dx": 8,
     "label": "snake mamba easterngreen (anf)",
     "name": "Snake Mamba Easterngreen (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b71",
  "group": "P19 HIS PICKS",
  "title": "SNAKE",
  "look": "LEFT to RIGHT: SNAKE MILK (ANF), SNAKE PYTHON GREENTREE (ANF), SNAKE PYTHON PASTEL (ANF), SNAKE PYTHON ROYAL (ANF), SNAKE RATTLE DIAMONDBACK (ANF).",
  "rig": {
   "mob": "pw:snake_python_pastel_anf",
   "label": "snake python pastel (anf)",
   "name": "Snake Python Pastel (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:snake_milk_anf",
     "dx": -8,
     "label": "snake milk (anf)",
     "name": "Snake Milk (AnF)"
    },
    {
     "mob": "pw:snake_python_greentree_anf",
     "dx": -4,
     "label": "snake python greentree (anf)",
     "name": "Snake Python Greentree (AnF)"
    },
    {
     "mob": "pw:snake_python_royal_anf",
     "dx": 4,
     "label": "snake python royal (anf)",
     "name": "Snake Python Royal (AnF)"
    },
    {
     "mob": "pw:snake_rattle_diamondback_anf",
     "dx": 8,
     "label": "snake rattle diamondback (anf)",
     "name": "Snake Rattle Diamondback (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b72",
  "group": "P19 HIS PICKS",
  "title": "SNAKE",
  "look": "LEFT to RIGHT: SNAKE RATTLE TIMBER (ANF), SNAKE VIPER BLUE (ANF), SNAKE VIPER HORNED (ANF), SNAKE WATER BROWN (ANF), SNAKE WATER PLAINBELLIED (ANF).",
  "rig": {
   "mob": "pw:snake_viper_horned_anf",
   "label": "snake viper horned (anf)",
   "name": "Snake Viper Horned (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:snake_rattle_timber_anf",
     "dx": -8,
     "label": "snake rattle timber (anf)",
     "name": "Snake Rattle Timber (AnF)"
    },
    {
     "mob": "pw:snake_viper_blue_anf",
     "dx": -4,
     "label": "snake viper blue (anf)",
     "name": "Snake Viper Blue (AnF)"
    },
    {
     "mob": "pw:snake_water_brown_anf",
     "dx": 4,
     "label": "snake water brown (anf)",
     "name": "Snake Water Brown (AnF)"
    },
    {
     "mob": "pw:snake_water_plainbellied_anf",
     "dx": 8,
     "label": "snake water plainbellied (anf)",
     "name": "Snake Water Plainbellied (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b73",
  "group": "P19 HIS PICKS",
  "title": "SNAKE",
  "look": "LEFT to RIGHT: SNAKE CORAL (WA), SNAKE SCARLET (WA), SNAKE (WA).",
  "rig": {
   "mob": "pw:snake_scarlet_wa",
   "label": "snake scarlet (wa)",
   "name": "Snake Scarlet (WA)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:snake_coral_wa",
     "dx": -4,
     "label": "snake coral (wa)",
     "name": "Snake Coral (WA)"
    },
    {
     "mob": "pw:snake_wa",
     "dx": 4,
     "label": "snake (wa)",
     "name": "Snake (WA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b74",
  "group": "P19 HIS PICKS",
  "title": "SNAPPING TURTLE \u00b7 SQUIRREL",
  "look": "LEFT to RIGHT: SNAPPING TURTLE (WWA), SQUIRREL GREY (ANF), SQUIRREL RED (ANF).",
  "rig": {
   "mob": "pw:squirrel_grey_anf",
   "label": "squirrel grey (anf)",
   "name": "Squirrel Grey (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:snapping_turtle_wwa",
     "dx": -4,
     "label": "snapping turtle (wwa)",
     "name": "Snapping Turtle (WWA)"
    },
    {
     "mob": "pw:squirrel_red_anf",
     "dx": 4,
     "label": "squirrel red (anf)",
     "name": "Squirrel Red (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b75",
  "group": "P19 HIS PICKS",
  "title": "STORK",
  "look": "LEFT to RIGHT: STORK ADJUTANT (ANF), STORK BLACK (ANF), STORK BLACKNECKED (ANF), STORK ORIENTAL (ANF), STORK PAINTED (ANF).",
  "rig": {
   "mob": "pw:stork_blacknecked_anf",
   "label": "stork blacknecked (anf)",
   "name": "Stork Blacknecked (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:stork_adjutant_anf",
     "dx": -8,
     "label": "stork adjutant (anf)",
     "name": "Stork Adjutant (AnF)"
    },
    {
     "mob": "pw:stork_black_anf",
     "dx": -4,
     "label": "stork black (anf)",
     "name": "Stork Black (AnF)"
    },
    {
     "mob": "pw:stork_oriental_anf",
     "dx": 4,
     "label": "stork oriental (anf)",
     "name": "Stork Oriental (AnF)"
    },
    {
     "mob": "pw:stork_painted_anf",
     "dx": 8,
     "label": "stork painted (anf)",
     "name": "Stork Painted (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b76",
  "group": "P19 HIS PICKS",
  "title": "STORK",
  "look": "LEFT to RIGHT: STORK SADDLEBILLED (ANF), STORK WHITE (ANF), STORK WOOD (ANF).",
  "rig": {
   "mob": "pw:stork_white_anf",
   "label": "stork white (anf)",
   "name": "Stork White (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:stork_saddlebilled_anf",
     "dx": -4,
     "label": "stork saddlebilled (anf)",
     "name": "Stork Saddlebilled (AnF)"
    },
    {
     "mob": "pw:stork_wood_anf",
     "dx": 4,
     "label": "stork wood (anf)",
     "name": "Stork Wood (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b77",
  "group": "P19 HIS PICKS",
  "title": "SWAN \u00b7 TAPIR \u00b7 TERMITE",
  "look": "LEFT to RIGHT: SWAN BLACK (ANF), SWAN WHITE (ANF), SWAN (WWA), TAPIR (WS), TERMITE (ANF).",
  "rig": {
   "mob": "pw:swan_wwa",
   "label": "swan (wwa)",
   "name": "Swan (WWA)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:swan_black_anf",
     "dx": -8,
     "label": "swan black (anf)",
     "name": "Swan Black (AnF)"
    },
    {
     "mob": "pw:swan_white_anf",
     "dx": -4,
     "label": "swan white (anf)",
     "name": "Swan White (AnF)"
    },
    {
     "mob": "pw:tapir_ws",
     "dx": 4,
     "label": "tapir (ws)",
     "name": "Tapir (WS)"
    },
    {
     "mob": "pw:termite_anf",
     "dx": 8,
     "label": "termite (anf)",
     "name": "Termite (AnF)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b78",
  "group": "P19 HIS PICKS",
  "title": "TIGER",
  "look": "LEFT to RIGHT: TIGER BENGAL (ANF), TIGER SIBERIAN (ANF), TIGER SOUTHCHINA (ANF), TIGER (WA), WHITE TIGER (WA).",
  "rig": {
   "mob": "pw:tiger_southchina_anf",
   "label": "tiger southchina (anf)",
   "name": "Tiger Southchina (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:tiger_bengal_anf",
     "dx": -8,
     "label": "tiger bengal (anf)",
     "name": "Tiger Bengal (AnF)"
    },
    {
     "mob": "pw:tiger_siberian_anf",
     "dx": -4,
     "label": "tiger siberian (anf)",
     "name": "Tiger Siberian (AnF)"
    },
    {
     "mob": "pw:tiger_wa",
     "dx": 4,
     "label": "tiger (wa)",
     "name": "Tiger (WA)"
    },
    {
     "mob": "pw:white_tiger_wa",
     "dx": 8,
     "label": "white tiger (wa)",
     "name": "White Tiger (WA)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b79",
  "group": "P19 HIS PICKS",
  "title": "TIGER",
  "look": "LEFT to RIGHT: TIGER (WS).",
  "rig": {
   "mob": "pw:tiger_ws",
   "label": "tiger (ws)",
   "name": "Tiger (WS)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b80",
  "group": "P19 HIS PICKS",
  "title": "TORTOISE",
  "look": "LEFT to RIGHT: TORTOISE (YSAV).",
  "rig": {
   "mob": "pw:tortoise_ysav",
   "label": "tortoise (ysav)",
   "name": "Tortoise (YSav)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [],
   "roof": true
  }
 },
 {
  "id": "b81",
  "group": "P19 HIS PICKS",
  "title": "TOUCAN",
  "look": "LEFT to RIGHT: TOUCAN ARACARI (ANF), TOUCAN CHANNELBILLED (ANF), TOUCAN TOCO (ANF), TOUCAN (WA), TOUCAN (YTRI).",
  "rig": {
   "mob": "pw:toucan_toco_anf",
   "label": "toucan toco (anf)",
   "name": "Toucan Toco (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 6,
   "row": [
    {
     "mob": "pw:toucan_aracari_anf",
     "dx": -8,
     "label": "toucan aracari (anf)",
     "name": "Toucan Aracari (AnF)"
    },
    {
     "mob": "pw:toucan_channelbilled_anf",
     "dx": -4,
     "label": "toucan channelbilled (anf)",
     "name": "Toucan Channelbilled (AnF)"
    },
    {
     "mob": "pw:toucan_wa",
     "dx": 4,
     "label": "toucan (wa)",
     "name": "Toucan (WA)"
    },
    {
     "mob": "pw:toucan_ytri",
     "dx": 8,
     "label": "toucan (ytri)",
     "name": "Toucan (YTri)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b82",
  "group": "P19 HIS PICKS",
  "title": "TURKEY \u00b7 VULTURE \u00b7 WALRUS \u00b7 YAK",
  "look": "LEFT to RIGHT: TURKEY (WA), VULTURE KING (ANF), VULTURE REDHEADED (ANF), WALRUS (ANF), YAK (WS).",
  "rig": {
   "mob": "pw:vulture_redheaded_anf",
   "label": "vulture redheaded (anf)",
   "name": "Vulture Redheaded (AnF)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:turkey_wa",
     "dx": -8,
     "label": "turkey (wa)",
     "name": "Turkey (WA)"
    },
    {
     "mob": "pw:vulture_king_anf",
     "dx": -4,
     "label": "vulture king (anf)",
     "name": "Vulture King (AnF)"
    },
    {
     "mob": "pw:walrus_anf",
     "dx": 4,
     "label": "walrus (anf)",
     "name": "Walrus (AnF)"
    },
    {
     "mob": "pw:yak_ws",
     "dx": 8,
     "label": "yak (ws)",
     "name": "Yak (WS)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b83",
  "group": "P19 HIS PICKS",
  "title": "ZEBRA",
  "look": "LEFT to RIGHT: ZEBRA MOUNTAIN (ANF), ZEBRA PLAINS (ANF), ZEBRA (WA), ZEBRA (YSAV).",
  "rig": {
   "mob": "pw:zebra_wa",
   "label": "zebra (wa)",
   "name": "Zebra (WA)",
   "half": 10,
   "halfz": 3,
   "height": 5,
   "row": [
    {
     "mob": "pw:zebra_mountain_anf",
     "dx": -8,
     "label": "zebra mountain (anf)",
     "name": "Zebra Mountain (AnF)"
    },
    {
     "mob": "pw:zebra_plains_anf",
     "dx": -4,
     "label": "zebra plains (anf)",
     "name": "Zebra Plains (AnF)"
    },
    {
     "mob": "pw:zebra_ysav",
     "dx": 4,
     "label": "zebra (ysav)",
     "name": "Zebra (YSav)"
    }
   ],
   "roof": true
  }
 },
 {
  "id": "b84",
  "group": "P19 WATER",
  "title": "HAMMERHEAD SHARK \u00b7 JELLYFISH",
  "look": "LEFT to RIGHT: HAMMERHEAD SHARK (WA), JELLYFISH (YTRI).",
  "rig": {
   "mob": "pw:jellyfish_ytri",
   "label": "jellyfish (ytri)",
   "name": "Jellyfish (YTri)",
   "half": 5,
   "halfz": 3,
   "height": 7,
   "row": [
    {
     "mob": "pw:hammerhead_shark_wa",
     "dx": -3,
     "label": "hammerhead shark (wa)",
     "name": "Hammerhead Shark (WA)"
    }
   ],
   "water": true,
   "depth": 3
  }
 },
 {
  "id": "b85",
  "group": "P19 WATER",
  "title": "OCTOPUS",
  "look": "LEFT to RIGHT: OCTOPUS BLUERINGED (ANF), OCTOPUS COMMON (ANF), OCTOPUS PACIFICGIANT (ANF).",
  "rig": {
   "mob": "pw:octopus_common_anf",
   "label": "octopus common (anf)",
   "name": "Octopus Common (AnF)",
   "half": 5,
   "halfz": 3,
   "height": 7,
   "row": [
    {
     "mob": "pw:octopus_blueringed_anf",
     "dx": -3,
     "label": "octopus blueringed (anf)",
     "name": "Octopus Blueringed (AnF)"
    },
    {
     "mob": "pw:octopus_pacificgiant_anf",
     "dx": 3,
     "label": "octopus pacificgiant (anf)",
     "name": "Octopus Pacificgiant (AnF)"
    }
   ],
   "water": true,
   "depth": 3
  }
 },
 {
  "id": "b86",
  "group": "P19 WATER",
  "title": "ORCA",
  "look": "LEFT to RIGHT: ORCA (WA), ORCA (WWA).",
  "rig": {
   "mob": "pw:orca_wwa",
   "label": "orca (wwa)",
   "name": "Orca (WWA)",
   "half": 10,
   "halfz": 5,
   "height": 7,
   "row": [
    {
     "mob": "pw:orca_wa",
     "dx": -8,
     "label": "orca (wa)",
     "name": "Orca (WA)"
    }
   ],
   "water": true,
   "depth": 4
  }
 },
 {
  "id": "b87",
  "group": "P19 WATER",
  "title": "ORCA",
  "look": "LEFT to RIGHT: ORCA (YTRI).",
  "rig": {
   "mob": "pw:orca_ytri",
   "label": "orca (ytri)",
   "name": "Orca (YTri)",
   "half": 10,
   "halfz": 5,
   "height": 7,
   "row": [],
   "water": true,
   "depth": 4
  }
 },
 {
  "id": "b88",
  "group": "P19 WATER",
  "title": "RIVER DOLPHIN",
  "look": "LEFT to RIGHT: RIVER DOLPHIN (YTRI).",
  "rig": {
   "mob": "pw:river_dolphin_ytri",
   "label": "river dolphin (ytri)",
   "name": "River Dolphin (YTri)",
   "half": 5,
   "halfz": 3,
   "height": 7,
   "row": [],
   "water": true,
   "depth": 3
  }
 },
 {
  "id": "b89",
  "group": "P19 WATER",
  "title": "SHARK",
  "look": "LEFT to RIGHT: SHARK GREATWHITE (ANF), SHARK HAMMERHEAD (ANF).",
  "rig": {
   "mob": "pw:shark_hammerhead_anf",
   "label": "shark hammerhead (anf)",
   "name": "Shark Hammerhead (AnF)",
   "half": 10,
   "halfz": 5,
   "height": 7,
   "row": [
    {
     "mob": "pw:shark_greatwhite_anf",
     "dx": -8,
     "label": "shark greatwhite (anf)",
     "name": "Shark Greatwhite (AnF)"
    }
   ],
   "water": true,
   "depth": 4
  }
 },
 {
  "id": "b90",
  "group": "P19 WATER",
  "title": "SHARK",
  "look": "LEFT to RIGHT: SHARK LEMON (ANF), SHARK TIGER (ANF).",
  "rig": {
   "mob": "pw:shark_tiger_anf",
   "label": "shark tiger (anf)",
   "name": "Shark Tiger (AnF)",
   "half": 10,
   "halfz": 5,
   "height": 7,
   "row": [
    {
     "mob": "pw:shark_lemon_anf",
     "dx": -8,
     "label": "shark lemon (anf)",
     "name": "Shark Lemon (AnF)"
    }
   ],
   "water": true,
   "depth": 4
  }
 },
 {
  "id": "b91",
  "group": "P19 WATER",
  "title": "SHARK",
  "look": "LEFT to RIGHT: SHARK (WA), TIGER SHARK (WA).",
  "rig": {
   "mob": "pw:tiger_shark_wa",
   "label": "tiger shark (wa)",
   "name": "Tiger Shark (WA)",
   "half": 10,
   "halfz": 5,
   "height": 7,
   "row": [
    {
     "mob": "pw:shark_wa",
     "dx": -8,
     "label": "shark (wa)",
     "name": "Shark (WA)"
    }
   ],
   "water": true,
   "depth": 4
  }
 },
 {
  "id": "b92",
  "group": "P19 WATER",
  "title": "SHARK",
  "look": "LEFT to RIGHT: WHITE SHARK (WA).",
  "rig": {
   "mob": "pw:white_shark_wa",
   "label": "white shark (wa)",
   "name": "White Shark (WA)",
   "half": 10,
   "halfz": 5,
   "height": 7,
   "row": [],
   "water": true,
   "depth": 4
  }
 },
 {
  "id": "b93",
  "group": "P19 WATER",
  "title": "SHRIMP \u00b7 STARFISH",
  "look": "LEFT to RIGHT: SHRIMP (WA), SHELLFISH STARFISH (ANF).",
  "rig": {
   "mob": "pw:shellfish_starfish_anf",
   "label": "shellfish starfish (anf)",
   "name": "Shellfish Starfish (AnF)",
   "half": 5,
   "halfz": 3,
   "height": 7,
   "row": [
    {
     "mob": "pw:shrimp_wa",
     "dx": -3,
     "label": "shrimp (wa)",
     "name": "Shrimp (WA)"
    }
   ],
   "water": true,
   "depth": 3
  }
 },
 {
  "id": "b94",
  "group": "P19 WATER",
  "title": "STINGRAY",
  "look": "LEFT to RIGHT: STINGRAY (WA), STINGRAY (WWA).",
  "rig": {
   "mob": "pw:stingray_wwa",
   "label": "stingray (wwa)",
   "name": "Stingray (WWA)",
   "half": 10,
   "halfz": 5,
   "height": 7,
   "row": [
    {
     "mob": "pw:stingray_wa",
     "dx": -8,
     "label": "stingray (wa)",
     "name": "Stingray (WA)"
    }
   ],
   "water": true,
   "depth": 4
  }
 },
 {
  "id": "b95",
  "group": "P19 WATER",
  "title": "STINGRAY",
  "look": "LEFT to RIGHT: STINGRAY (YTRI).",
  "rig": {
   "mob": "pw:stingray_ytri",
   "label": "stingray (ytri)",
   "name": "Stingray (YTri)",
   "half": 10,
   "halfz": 5,
   "height": 7,
   "row": [],
   "water": true,
   "depth": 4
  }
 },
 {
  "id": "b96",
  "group": "P19 WATER",
  "title": "WHALE",
  "look": "LEFT to RIGHT: WHALE (WA), WHALE (WWA).",
  "rig": {
   "mob": "pw:whale_wwa",
   "label": "whale (wwa)",
   "name": "Whale (WWA)",
   "half": 10,
   "halfz": 5,
   "height": 7,
   "row": [
    {
     "mob": "pw:whale_wa",
     "dx": -8,
     "label": "whale (wa)",
     "name": "Whale (WA)"
    }
   ],
   "water": true,
   "depth": 4
  }
 }
];
const Q0 = { id: "q0", group: "P19 SETUP", title: "P19 HIS PICKS: PHONE HOSTS, PS5 JOINS (VIBRANT VISUALS), FLAT GROUND, FACE NORTH",
  body: lines("Packs (on the phone): RP-07 v1.4.34 + PW-StripMine BP v1.3.9 (they hold everything of v1.4.32 / v1.3.7) - always together; PW-TestRunner BP v0.5.7 at the bottom. " +
    "Use a COPY of the test world; host on the phone, join on the PS5 with Vibrant Visuals ON. Creative.\n" +
    "Content log after load: 'PW Test Runner BP v0.5.7'.\nStand on big FLAT open ground (15 blocks clear each side, 15 NORTH) and FACE NORTH.\nPASS = ready."),
  setup: [{ daytime: "noon" }, { weather: "clear" }] };
const STEPS19 = P19_DATA.map((d) => ({ id: d.id, group: d.group, title: d.title,
  body: lines(`${d.look}\n${LOOK}\nSHOT of the pen from the front (south).\n${PASSN}`), setup: [{ cmd: CLEAR }, { rig: d.rig }] }));
const Q9 = { id: "q9", group: "P19 DONE", title: "P19: ALL CLEAR - UPLOAD",
  body: lines("The last pen is removed when you pass this step. Upload any shots and copy the content log (or /scriptevent pw:test report p19).\nPASS = uploaded (or about to)."),
  setup: [{ cmd: CLEAR }, { daytime: "noon" }] };
export const P19_STEPS = [Q0, ...STEPS19, Q9];
export const P19_INDEX = Object.fromEntries(P19_STEPS.map((s, i) => [s.id, i]));
