source=skybox:the_nether/sky002.png
startFadeIn=11:58
endFadeIn=11:59
startFadeOut=12:00
endFadeOut=12:01
blend=alpha
rotate=true
speed=1
axis=0.0 -1.0 0.0
transition=10
heights=0-10000
biomes=warped_forest soul_sand_valley