// civ_verify.js — CIVITAS structure verifier, shared by the BDS harness and the in-game TestRunner commands.
//   verifyFile(id, man)                      : the structure FILE as the engine reads it, every cell vs the manifest
//   placeAndVerify(id, man, dim, at, rot)    : place it, then compare the world (every cell's block; states at
//                                              rotation 0) and the marker / hatch entities (each in its rotated cell)
// Manifest (generated by civgen.py): { name, size:[x,y,z], datum_y, pal:[[name,{states}],...], idx:[...x-major, z
// fastest], ents:[{id, fam?, kind?, n?, hinge?, cell:[x, feet, z]}] }.
import { world, system } from "@minecraft/server";

export const ROTATIONS = ["None", "Rotate90", "Rotate180", "Rotate270"];
const STEPS = { None: 0, Rotate90: 1, Rotate180: 2, Rotate270: 3 };

const sleep = (t) => new Promise((r) => system.runTimeout(r, t));

/** local (x, z) of the saved file -> local offset after a clockwise rotation (BDS-verified for Rotate90 2026-10-02). */
export function rotXZ(x, z, sx, sz, rot) {
  if (rot === "Rotate90") return [sz - 1 - z, x];
  if (rot === "Rotate180") return [sx - 1 - x, sz - 1 - z];
  if (rot === "Rotate270") return [z, sx - 1 - x];
  return [x, z];
}

function statesMatch(want, got) {
  for (const [k, v] of Object.entries(want)) {
    const g = got[k];
    if (typeof v === "boolean" || typeof g === "boolean") {
      if (Boolean(v) !== Boolean(g)) return `${k}=${g} (want ${v})`;
    } else if (g !== v) {
      return `${k}=${g} (want ${v})`;
    }
  }
  return null;
}

function* cells(man) {
  const [sx, sy, sz] = man.size;
  let i = 0;
  for (let x = 0; x < sx; x++) for (let y = 0; y < sy; y++) for (let z = 0; z < sz; z++) {
    const p = man.idx[i++];
    if (p >= 0) yield [x, y, z, man.pal[p]];
  }
}

export function verifyFile(id, man) {
  const s = world.structureManager.get(id);
  if (!s) return { ok: false, id, err: "structure not found" };
  const bad = [];
  let n = 0;
  if (s.size.x !== man.size[0] || s.size.y !== man.size[1] || s.size.z !== man.size[2]) {
    return { ok: false, id, err: `size ${s.size.x}x${s.size.y}x${s.size.z} want ${man.size.join("x")}` };
  }
  for (const [x, y, z, [name, states]] of cells(man)) {
    n++;
    const p = s.getBlockPermutation({ x, y, z });
    if (!p) { bad.push([x, y, z, "void", name]); continue; }
    if (p.type.id !== name) { bad.push([x, y, z, p.type.id, name]); continue; }
    const why = statesMatch(states, p.getAllStates());
    if (why) bad.push([x, y, z, name, why]);
  }
  return { ok: bad.length === 0, id, cells: n, bad: bad.length, first: bad.slice(0, 8) };
}

async function loaded(dim, loc) {
  for (let k = 0; k < 200; k++) {
    try { if (dim.getBlock(loc)) return true; } catch { /* not loaded yet */ }
    await sleep(5);
  }
  return false;
}

export async function placeAndVerify(id, man, dim, at, rot = "None") {
  const [sx, sy, sz] = man.size;
  const [rx, rz] = (rot === "Rotate90" || rot === "Rotate270") ? [sz, sx] : [sx, sz];
  if (!(await loaded(dim, at)) || !(await loaded(dim, { x: at.x + rx - 1, y: at.y + sy - 1, z: at.z + rz - 1 }))) {
    return { ok: false, id, rot, err: "area not loaded" };
  }
  world.structureManager.place(id, dim, at, { rotation: rot, includeEntities: true, includeBlocks: true });
  await sleep(4);
  const bad = [];
  let n = 0;
  for (const [x, y, z, [name, states]] of cells(man)) {
    n++;
    const [ox, oz] = rotXZ(x, z, sx, sz, rot);
    let b;
    try { b = dim.getBlock({ x: at.x + ox, y: at.y + y, z: at.z + oz }); } catch { b = undefined; }
    if (!b) { bad.push([x, y, z, "unloaded", name]); continue; }
    if (b.typeId !== name) { bad.push([x, y, z, b.typeId, name]); continue; }
    if (rot === "None") {
      const why = statesMatch(states, b.permutation.getAllStates());
      if (why) bad.push([x, y, z, name, why]);
    }
  }
  // entities: every manifest entity must stand in its (rotated) cell
  const found = dim.getEntities({ location: at, volume: { x: rx - 1, y: sy - 1, z: rz - 1 } })
    .filter((e) => e.typeId === "pw:marker" || e.typeId === "pw:hatch_lid");
  const used = new Set();
  const missing = [];
  for (const m of man.ents) {
    const [ox, oz] = rotXZ(m.cell[0], m.cell[2], sx, sz, rot);
    const want = { x: at.x + ox, y: at.y + m.cell[1] + man.datum_y, z: at.z + oz };
    const hit = found.find((e, k) => !used.has(k) && e.typeId === m.id &&
      Math.floor(e.location.x) === want.x && Math.floor(e.location.y) === want.y && Math.floor(e.location.z) === want.z &&
      (m.id !== "pw:marker" || (e.hasTag(`civ:kind:${m.kind}`) && e.hasTag(`civ:n:${m.n}`))) && used.add(k));
    if (!hit) missing.push(m.id === "pw:marker" ? `${m.fam}:${m.kind}#${m.n}@${m.cell}` : `${m.id}@${m.cell}`);
  }
  return {
    ok: bad.length === 0 && missing.length === 0 && found.length === man.ents.length, id, rot, cells: n,
    bad: bad.length, first: bad.slice(0, 6), entities: { want: man.ents.length, found: found.length, missing: missing.slice(0, 8) },
  };
}

/** hinge sides are WORLD sides: a structure turned N quarter turns turns its hatch hinges N steps clockwise. */
export function turnHinges(dim, at, man, rot) {
  const steps = STEPS[rot];
  if (!steps) return 0;
  let n = 0;
  const [sx, , sz] = man.size;
  for (const m of man.ents) {
    if (m.id !== "pw:hatch_lid") continue;
    const [ox, oz] = rotXZ(m.cell[0], m.cell[2], sx, sz, rot);
    const cell = { x: at.x + ox, y: at.y + m.cell[1] + man.datum_y, z: at.z + oz };
    for (const e of dim.getEntitiesAtBlockLocation(cell)) {
      if (e.typeId !== "pw:hatch_lid") continue;
      e.setProperty("pw:hinge", (m.hinge + steps) % 4);
      n++;
    }
  }
  return n;
}

