// pw_civ_court_data.js — GENERATED by tools/palace_beds.py (1.3.229 role beds): the palace pieces' beds by room role.
// A bed = one double bed (2 bed blocks). Roles: lord, noble, servant, guard, clerk, cell (never a home).
export const PALACE_BEDS = {"ne": {"child": 4, "guard": 4, "lord": 1, "noble": 3, "servant": 4}, "nw": {"child": 3, "noble": 3, "servant": 12}, "se": {"child": 5, "clerk": 7, "guard": 3, "noble": 5, "servant": 22}, "sw": {"cell": 4, "clerk": 7, "guard": 9, "servant": 16}};
