#!/usr/bin/env python3
"""build_rp01_124.py — RP-01 1.3.124 from 1.3.123: the falling-tree CARBON COPIES of the birch v3 templates (BP-02 1.3.224:
the trunk ends one block into the crown, his 16:50). The 544 copies are regenerated by tools/ft_tpl_gen_lite.py with
1.3.121's meshing arguments; every non-birch copy must come out byte-identical (asserted), only birch_* change.
Usage: python3 tools/build_rp01_124.py   (rp01-124 must not exist; BP = _build/bp02-224)"""
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

B = Path("/home/claude/_build")
SRC, DST, BP = B / "rp01-123", B / "rp01-124", B / "bp02-224"
ARGS = ["--maxb=8", "--clusters=12", "--runfrom=3", "--close=3"]          # exactly 1.3.121's meshing
VERSION = [1, 3, 124]


def digests(root):
    d = root / "models/entity/ft_tpl"
    return {p.name: hashlib.md5(p.read_bytes()).hexdigest() for p in sorted(d.glob("*.json"))}


def main():
    if DST.exists():
        raise SystemExit(f"never rebuild {DST}")
    before = digests(SRC)
    shutil.copytree(SRC, DST)
    r = subprocess.run([sys.executable, "/home/claude/tools/ft_tpl_gen_lite.py", str(DST), str(BP)] + ARGS, capture_output=True, text=True)
    print(r.stdout[-1500:])
    assert r.returncode == 0, r.stderr[-1500:]
    after = digests(DST)
    assert set(before) == set(after), (set(before) ^ set(after))
    changed = sorted(k for k in after if after[k] != before[k])
    others = [k for k in changed if not k.startswith("birch_")]
    assert not others, f"non-birch copies changed: {others[:8]}"
    mp = DST / "manifest.json"
    m = json.loads(mp.read_text())
    m["header"]["version"] = VERSION
    m["header"]["name"] = m["header"]["name"].replace("1.3.123", "1.3.124")
    for mod in m["modules"]:
        mod["version"] = VERSION
    m["header"]["description"] = ("v1.3.124 (2026-10-05) BIRCH v3 falling copies: a felled birch shows the shortened trunk (it ends at the crown's "
                                  "base; needs BP-02 1.3.224). Includes all of " + m["header"]["description"])
    mp.write_text(json.dumps(m, indent=1))
    print(f"DONE {DST}: {len(changed)} birch copies regenerated, {len(after) - len(changed)} others byte-identical")


if __name__ == "__main__":
    main()
