#!/usr/bin/env python3
"""build_rp01_125.py — RP-01 1.3.125 from 1.3.124: the falling-tree CARBON COPIES of the program-228 tree templates
(BP-02 1.3.228 overlay, tools/bp02_overlay_228/structures/pw/trees): the v4 trunk-tip rule (trunk tip under the crown
apex; oak elder + pale oak stag limbs and the oak old stag head removed; pale oak lower / flatter) and the jungle_young
doubled-root fix. The 544 copies are regenerated by tools/ft_tpl_gen_lite.py with 1.3.121's meshing arguments (the
build_rp01_124 recipe) from a READ-ONLY view of BP-02 = bp02-227 blocks + bp02-227 trees with the overlay's files swapped in
(bp02-227 / bp02-228 are never written). Asserted: the file set is unchanged; exactly the overlay's templates' copies change;
every other file of the pack (the other copies, atlases, render controllers, ...) is byte-identical except manifest.json.
Usage: python3 tools/build_rp01_125.py   (rp01-125 must not exist)"""
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

B = Path("/home/claude/_build")
SRC, DST = B / "rp01-124", B / "rp01-125"
BP = B / "bp02-227"
OVERLAY = Path("/home/claude/tools/bp02_overlay_228/structures/pw/trees")
SCRATCH = Path("/tmp/claude-0/-home-claude/c0a4a7ef-9c52-560d-ac77-bcf688f4b3d2/scratchpad/tree228")
ARGS = ["--maxb=8", "--clusters=12", "--runfrom=3", "--close=3"]          # exactly 1.3.121's meshing
VERSION = [1, 3, 125]
FT_INDEX_DOC = Path("/home/claude/_docs/fell/ft_tpl_index.json")         # ft_tpl_gen_lite rewrites it (side effect)


def md5(p):
    return hashlib.md5(Path(p).read_bytes()).hexdigest()


def tree_digests(root):
    return {str(p.relative_to(root)): md5(p) for p in sorted(root.rglob("*")) if p.is_file()}


def main():
    if DST.exists():
        raise SystemExit(f"never rebuild {DST}")
    ov = sorted(p.stem for p in OVERLAY.glob("*.mcstructure"))
    assert ov, "empty overlay"
    ship = {p.stem for p in (BP / "structures/pw/trees").glob("*.mcstructure")}
    assert set(ov) <= ship and len(ship) == 544, "overlay names must be shipped template names"
    SCRATCH.mkdir(parents=True, exist_ok=True)
    view = Path(tempfile.mkdtemp(prefix="bpview_", dir=SCRATCH))
    try:
        shutil.copytree(BP / "blocks", view / "blocks")                   # 11 MB, read by ft_tpl_gen_lite (trunk widths)
        trees = view / "structures/pw/trees"
        trees.mkdir(parents=True)
        for p in sorted((BP / "structures/pw/trees").glob("*.mcstructure")):
            os.symlink(OVERLAY / p.name if p.stem in ov else p, trees / p.name)
        before = tree_digests(SRC)
        doc_before = FT_INDEX_DOC.read_bytes() if FT_INDEX_DOC.exists() else None
        shutil.copytree(SRC, DST)
        r = subprocess.run([sys.executable, "/home/claude/tools/ft_tpl_gen_lite.py", str(DST), str(view)] + ARGS,
                           capture_output=True, text=True)
        print(r.stdout[-1500:])
        assert r.returncode == 0, r.stderr[-1500:]
    finally:
        shutil.rmtree(view, ignore_errors=True)
    if doc_before is not None:
        FT_INDEX_DOC.with_suffix(".pre125.json").write_bytes(doc_before)
    after = tree_digests(DST)
    assert set(before) == set(after), sorted(set(before) ^ set(after))[:10]
    changed = sorted(k for k in after if after[k] != before[k])
    want = sorted(f"models/entity/ft_tpl/{s}.geo.json" for s in ov)
    assert changed == want, f"unexpected: {sorted(set(changed) ^ set(want))[:10]}"
    mp = DST / "manifest.json"
    m = json.loads(mp.read_text())
    assert m["header"]["version"] == [1, 3, 124]
    m["header"]["version"] = VERSION
    m["header"]["name"] = m["header"]["name"].replace("1.3.124", "1.3.125")
    for mod in m["modules"]:
        mod["version"] = VERSION
    m["header"]["description"] = ("v1.3.125 (2026-10-06) program 228 TREE falling copies: trunk tips sit under the crown (no bare leader, "
                                  "no stag limbs over oak elder / pale oak crowns, no oak old stag head; pale oak lower and flatter), "
                                  "jungle young without the doubled root (needs BP-02 1.3.228). Includes all of " + m["header"]["description"])[:1000]
    mp.write_text(json.dumps(m, indent=1))
    final = tree_digests(DST)
    assert sorted(k for k in final if final[k] != before[k]) == sorted(want + ["manifest.json"])
    print(f"DONE {DST}: {len(changed)} copies regenerated ({len(ov)} overlay templates), {544 - len(changed)} others byte-identical, "
          f"{len(final) - len(changed) - 1} other files byte-identical, manifest {VERSION}")


if __name__ == "__main__":
    main()
