#!/usr/bin/env python3
"""build_bp02_217.py — BP-02 1.3.217 from the frozen 1.3.216 (never rebuilt): the CARBON-COPY falling tree (D-C524).

His 13:57 / 14:03 rulings: (1) no lying log — the felled trunk drops as items along the line where it fell (F8 b reverted;
saplings / sticks / apples keep coming from the leaves as before); (2) the falling entity is the felled tree itself
(F10 = a, never built before): for a structure tree the script tells the entity WHICH template it is (ft:tpl), how far
the cut sits above the root (ft:lift = lowest falling log y - root y) and how the template is turned in the world
against the entity's yaw (ft:turn = 90 * root facing quarter turns - yaw; law proven in tools/ft_tpl_gen.py _selftest),
and spawns it over the ROOT cell centre so the template's cells line up. Trees without a template keep the old model.
Needs RP-01 1.3.119 (the 544 geometries). 1.3.215 (2-block tree search) stays HELD; its number is never reused."""
import json
import shutil
from pathlib import Path

B = Path("/home/claude/_build")
SRC, DST = B / "bp02-216", B / "bp02-217"
INDEX = Path("/home/claude/_docs/fell/ft_tpl_index.json")


def replace_once(text, old, new, what):
    if text.count(old) != 1:
        raise SystemExit(f"{what}: expected 1 match, found {text.count(old)}")
    return text.replace(old, new)


def main():
    if DST.exists():
        raise SystemExit(f"never rebuild {DST}")
    names = [e["name"] for e in json.loads(INDEX.read_text())]
    shutil.copytree(SRC, DST)

    # 1. entity properties
    ep = DST / "entities/falling_tree.json"
    e = json.loads(ep.read_text())
    props = e["minecraft:entity"]["description"]["properties"]
    props["ft:tpl"] = {"type": "int", "range": [-1, 1023], "default": -1, "client_sync": True}
    props["ft:lift"] = {"type": "int", "range": [0, 63], "default": 0, "client_sync": True}
    props["ft:turn"] = {"type": "int", "range": [-720, 720], "default": 0, "client_sync": True}
    if len(props) > 32:
        raise SystemExit(f"too many entity properties: {len(props)}")
    ep.write_text(json.dumps(e, indent=1))

    # 2. the template index module (template name -> geometry index in RP-01 1.3.119)
    (DST / "scripts/pw_ft_tpl_index.js").write_text(
        "// pw_ft_tpl_index.js — generated by tools/ft_tpl_gen.py (BP-02 1.3.217): falling-tree template -> RP-01 geometry index.\n"
        "// The order MUST match RP-01's render-controller array Array.tpl_geos (same generator run).\n"
        f"export const FT_TPL_NAMES = {json.dumps(names)};\n"
        "export const FT_TPL_INDEX = new Map(FT_TPL_NAMES.map((n, i) => [`pw:trees/${n}`, i]));\n")

    mj = DST / "scripts/main.js"
    js = mj.read_text()
    js = replace_once(js, 'import { weatherIn } from "./pw_weather.js";',
                      'import { FT_TPL_INDEX } from "./pw_ft_tpl_index.js"; // v1.3.217 carbon-copy falling tree (D-C524)\n'
                      'import { weatherIn } from "./pw_weather.js";', "import")

    # 3. spawn over the root cell for a template tree
    js = replace_once(js, """        let spawnX = stump.x + 0.5;
        let spawnZ = stump.z + 0.5;
        if (trunkWidth === 2) {""",
                      """        let spawnX = stump.x + 0.5;
        let spawnZ = stump.z + 0.5;
        // v1.3.217 (D-C524): a template tree falls as its own carbon copy, built around the template's ROOT cell
        const _ftTpl = (tplName && _verdict.root) ? FT_TPL_INDEX.get(tplName) : undefined;
        if (_ftTpl !== undefined) {
          spawnX = _verdict.root.x + 0.5;
          spawnZ = _verdict.root.z + 0.5;
          log(`[FT-COPY] template ${tplName} = geometry ${_ftTpl}; spawn over the root (${_verdict.root.x}, ${_verdict.root.z})`);
        } else if (trunkWidth === 2) {""", "spawn xz")

    # 4. tell the entity which tree it is (right after the existing wood_type property)
    js = replace_once(js, """        if (ent) {
          try { ent.setProperty("ft:wood_type", speciesIdx); }""",
                      """        if (ent && _ftTpl !== undefined) {
          try {
            const _dirQ = { north: 0, east: 1, south: 2, west: 3 }[_verdict.root.dir] ?? 0;
            let _turn = Math.round(90 * _dirQ - pick.yaw);
            while (_turn > 360) _turn -= 360;
            while (_turn < -360) _turn += 360;
            const _lift = Math.max(0, Math.min(63, stump.y - _verdict.root.y));
            ent.setProperty("ft:tpl", _ftTpl);
            ent.setProperty("ft:lift", _lift);
            ent.setProperty("ft:turn", _turn);
            log(`[FT-COPY] tpl=${_ftTpl} lift=${_lift} turn=${_turn} (root facing ${_verdict.root.dir}, yaw ${pick.yaw.toFixed(0)})`);
          } catch (e) { log(`[FT-COPY] setProperty err: ${e} -> old model`); try { ent.setProperty("ft:tpl", -1); } catch {} }
        }
        if (ent) {
          try { ent.setProperty("ft:wood_type", speciesIdx); }""", "set props")

    # 5. no lying log: the trunk drops as items along the fall line
    js = replace_once(js, """          // v1.3.206 his F8 = b: the trunk stays lying on the ground along the fall line; logs that cannot lie there
          // (and the branch logs) drop as items as before. Leaf litter + saplings + sticks + apples come from the leaves.
          let _laid = 0;
          try { _laid = placeLyingLog(dimension, stump, swFx, swFz, Math.min(trunkH, logs.length), SPECIES[speciesIdx].drop); }
          catch (e) { log(`lying log err: ${e}`); }
          dropItems(dimension, stump, SPECIES[speciesIdx].drop, logs.length - _laid);
          log(`[FELL] lying log ${_laid} block(s), ${logs.length - _laid} dropped as items`);""",
                      """          // v1.3.217 his 13:57 ruling (F8 b reverted): NO lying log. The trunk's logs drop as items along the line where
          // it came down (one per block of trunk, from 2 blocks past the stump), the branch logs at the crown's end.
          // Leaf litter + saplings + sticks + apples still come from the leaves.
          let _dropped = 0;
          try {
            const _n = logs.length;
            const _run = Math.max(1, Math.min(trunkH, _n));
            for (let i = 0; i < _n; i++) {
              const _d = 2 + Math.min(i, _run - 1);
              const _p = { x: Math.floor(stump.x + 0.5 + swFx * _d), y: stump.y, z: Math.floor(stump.z + 0.5 + swFz * _d) };
              dropItems(dimension, _p, SPECIES[speciesIdx].drop, 1);
              _dropped++;
            }
          } catch (e) { log(`fall-line drops err: ${e}`); dropItems(dimension, stump, SPECIES[speciesIdx].drop, logs.length - _dropped); }
          log(`[FELL] ${logs.length} log(s) dropped as items along the fall line (no lying log)`);""", "lying log")
    js = replace_once(js, 'const PW_BUILD = "1.3.216";', 'const PW_BUILD = "1.3.217";', "PW_BUILD")
    mj.write_text(js)

    cp = DST / "scripts/pw_companion.js"
    cp.write_text(replace_once(cp.read_text(), "companion v7 LOADED (pack v1.3.216 ", "companion v7 LOADED (pack v1.3.217 ", "C2 label"))

    # 6. manifest + deps (RP-01 1.3.119 needed)
    m = json.loads((DST / "manifest.json").read_text())
    m["header"]["version"] = [1, 3, 217]
    for mod in m["modules"]:
        mod["version"] = [1, 3, 217]
    m["header"]["name"] = "AbsolutRealism Tectonic BP v1.3.217"
    desc = m["header"]["description"]
    if not desc.startswith("v1.3.216 (2026-10-03) "):
        raise SystemExit("description prefix")
    m["header"]["description"] = ("v1.3.217 (2026-10-03) FALLING TREE: the tree falls as its own carbon copy (needs RP-01 1.3.119); no lying "
                                  "log - the logs drop as items along the fall line. Includes all of " + desc)[:1000]
    (DST / "manifest.json").write_text(json.dumps(m, indent=1))
    dep = DST / "PW-DEPENDENCIES.md"
    dep.write_text(replace_once(dep.read_text(), "v1.3.216 (oak plank wall at the Builder's Table only;",
                                "v1.3.217 (carbon-copy falling tree, needs RP-01 1.3.119; no lying log; oak plank wall at the Builder's Table only;",
                                "deps"))
    print(f"DONE {DST}: {len(names)} templates indexed")


if __name__ == "__main__":
    main()
