#!/usr/bin/env python3
"""build_rp01_121.py — RP-01 1.3.121 from the frozen 1.3.120 (never rebuilt): LIGHT falling copies (D-C526).
His 15:06 witness: the game closes during the load screen. RP-01 1.3.119 / 1.3.120 load 606k cubes (1.3.118: 98.5k).
The 544 copies are regenerated by tools/ft_tpl_gen_lite.py (greedy-merged leaf boxes over a tiled leaf region, merged
trunk runs, 12 silhouette clusters per tree) and the trunk render controller now reads the species atlas (bark lives in
it, pre-tinted with the old trunk colour). Everything else of 1.3.120 (thicker oak / jungle trunks, spruce forks) stays."""
import json
import shutil
import subprocess
import sys
from pathlib import Path

B = Path("/home/claude/_build")
SRC, DST, BP = B / "rp01-120", B / "rp01-121", B / "bp02-218"
ARGS = ["--maxb=8", "--clusters=12", "--runfrom=3", "--close=3"]


def main():
    if DST.exists():
        raise SystemExit(f"never rebuild {DST}")
    shutil.copytree(SRC, DST)
    r = subprocess.run([sys.executable, "/home/claude/tools/ft_tpl_gen_lite.py", str(DST), str(BP)] + ARGS, capture_output=True, text=True)
    print(r.stdout[-1500:], r.stderr[-1500:])
    if r.returncode != 0:
        raise SystemExit("lite generator failed")
    rcp = DST / "render_controllers/ft_tpl.json"
    rc = json.loads(rcp.read_text())
    t = rc["render_controllers"]["controller.render.ft_tpl_trunk"]
    can = rc["render_controllers"]["controller.render.ft_tpl_canopy"]
    t["arrays"]["textures"] = can["arrays"]["textures"]
    t["textures"] = can["textures"]
    t["color"] = {"r": "1.0", "g": "1.0", "b": "1.0"}
    t["materials"] = [{"*": "Material.default"}]
    rcp.write_text(json.dumps(rc, indent=1))
    mp = DST / "manifest.json"
    m = json.loads(mp.read_text())
    m["header"]["version"] = [1, 3, 121]
    for mod in m["modules"]:
        mod["version"] = [1, 3, 121]
    m["header"]["name"] = "AbsolutRealism Tectonic RP v1.3.121"
    desc = m["header"]["description"]
    if not desc.startswith("v1.3.120 (2026-10-03) "):
        raise SystemExit("description prefix")
    m["header"]["description"] = ("v1.3.121 (2026-10-03) LOAD FIX: the falling-tree copies are rebuilt light (about 70k boxes instead "
                                  "of 500k; 1.3.119/120 closed the game during loading). Includes all of " + desc)[:1000]
    mp.write_text(json.dumps(m, indent=1))
    print(f"DONE {DST}")


if __name__ == "__main__":
    main()
