#!/usr/bin/env python3
"""civ_village_data.py — the CIVITAS building table the village clock imports (BP-02 scripts/pw_civ_buildings.js).
For every roster building (from _staging/civ/manifests):
  size [sx, sy, sz] (saved file), datum_y (feet 0), stages (5),
  lids  [[x, feet_y, z, hinge]]            hatch lids: the clock turns their hinge by the rotation's quarter turns
  dir   [[x, y, z, name, {directional states}]]   every block with a direction-carrying state (cardinal_direction,
        facing_direction, direction, pillar_axis, pw:n/e/s/w): after a ROTATED stage is placed the clock checks each one
        and sets the rigidly-rotated state if the engine left it otherwise (the probe counts how many it had to set,
        which measures the engine's own rotation law for vanilla and custom blocks).
Usage: civ_village_data.py OUT_JS"""
import json
import sys
from pathlib import Path

MAN = Path("/home/claude/_staging/civ/manifests")
STAGES = Path("/home/claude/_staging/civ/stages")
DIRK = {"minecraft:cardinal_direction", "facing_direction", "direction", "pillar_axis", "pw:n", "pw:e", "pw:s", "pw:w"}
sys.path.insert(0, "/home/claude/tools")
import mcstructure as M  # noqa: E402

# D-C534 §4.2: a stage's BILL OF MATERIALS is read from its own blocks (one unit = one block), by class
def mat_class(name):
    n = name.replace("minecraft:", "")
    if n in ("air", "structure_void", "water", "dirt", "grass_block", "farmland", "grass_path", "gravel", "sand", "coarse_dirt", "podzol"):
        return None
    if n.startswith("pw:") or name.startswith("pw:"):
        n2 = name.replace("pw:", "")
        if "thatch" in n2 or "roof" in n2:
            return "thatch"
        if "ramp" in n2 or "manhole" in n2 or "frame" in n2:
            return "stone"
        if "hearth" in n2 or "flue" in n2:
            return "stone"
        return "planks"
    if "glass" in n:
        return "glass"
    if any(k in n for k in ("iron", "anvil", "chain", "lantern", "cauldron", "hopper", "rail", "bell", "grindstone", "smithing", "blast")):
        return "iron"
    if n.endswith("_log") or n.endswith("_wood") or n.endswith("_stem") or n == "log" or n == "log2":
        return "timber"
    if any(k in n for k in ("stone", "cobble", "andesite", "diorite", "granite", "brick", "deepslate", "furnace", "smoker", "stonecutter", "composter_stone")):
        return "stone"
    if "hay" in n or "wheat" in n:
        return "thatch"
    if any(k in n for k in ("plank", "door", "fence", "stairs", "slab", "trapdoor", "ladder", "chest", "barrel", "bed", "table", "lectern", "bookshelf", "sign", "composter", "loom", "crafting", "wool", "carpet", "bench", "campfire", "stair")):
        return "planks"
    return "planks"


def bom_of(stem):
    out = []
    for k in range(5):
        p = STAGES / f"{stem}_s{k}.mcstructure"
        counts = {}
        if p.exists():
            st = M.Structure.from_bytes(p.read_bytes())
            sx, sy, sz = st.size
            for x in range(sx):
                for y in range(sy):
                    for z in range(sz):
                        cell = st.get(x, y, z)
                        if cell is None:
                            continue
                        c = mat_class(cell[0])
                        if c:
                            counts[c] = counts.get(c, 0) + 1
        if k == 0 and "quarry" in stem:
            counts = {}                                   # the quarry's own pit is excavation, not a bill
        out.append(counts)
    return out


def table():
    out = {}
    for p in sorted(MAN.glob("*.json")):
        m = json.loads(p.read_text())
        stem = m["name"].split(":", 1)[1]
        out[m["name"]] = {
            "stem": stem, "size": m["size"], "datum_y": m["datum_y"], "stages": 5,
            "lids": [[*e["cell"], e["hinge"]] for e in m["entities"] if e["id"] == "pw:hatch_lid"],
            "door": next((e["cell"] for e in m["entities"] if e.get("fam") == "datum"), [0, 0, m["size"][2] // 2]),
            "work": sum(1 for e in m["entities"] if e.get("fam") == "station" and e.get("kind") not in ("door", "bed", "seat", "store")),
            "dir": [[x, y, z, n, {k: v for k, v in s.items() if k in DIRK}] for x, y, z, n, s in m["blocks"] if set(s) & DIRK],
            "bom": bom_of(stem),
            # C2.2: the storage blocks (ground floor first, then the cellar / loft): [x, y, z, id] in template coords
            "chests": sorted([[x, y, z, n] for x, y, z, n, s in m["blocks"] if n in ("minecraft:chest", "minecraft:barrel")],
                             key=lambda c: (abs(c[1] - m["datum_y"]), c[1], c[0], c[2])),
        }
    return out


if __name__ == "__main__":
    t = table()
    js = ("// generated by tools/civ_village_data.py from the CIVITAS roster manifests — do not edit by hand\n"
          "export const CIV_BUILDINGS = " + json.dumps(t, separators=(",", ":")) + ";\n")
    Path(sys.argv[1]).write_text(js)
    print(f"{len(t)} buildings, {sum(len(v['dir']) for v in t.values())} directional cells, "
          f"{sum(len(v['lids']) for v in t.values())} lids -> {sys.argv[1]} ({len(js):,} B)")
