#!/usr/bin/env python3
"""civ_pack.py — turn civgen manifests into the compact JS module the verifier imports, and build the BDS-only
civtest BP (structures + civ_verify.js + an auto-run main) for tools/bds_civtest.py.
Usage: civ_pack.py STAGE_DIR OUT_BP_DIR"""
import json
import shutil
import sys
import uuid
from pathlib import Path

SRC = Path("/home/claude/tools/civ_src")


def compact(man):
    """manifest blocks -> palette + flat index (x-major, y, z fastest), the layout the verifier walks."""
    sx, sy, sz = man["size"]
    pal, key, idx = [], {}, [-1] * (sx * sy * sz)
    for x, y, z, name, states in man["blocks"]:
        k = json.dumps([name, states], sort_keys=True)
        if k not in key:
            key[k] = len(pal)
            pal.append([name, states])
        idx[(x * sy + y) * sz + z] = key[k]
    return {"name": man["name"], "size": man["size"], "datum_y": man["datum_y"], "pal": pal, "idx": idx,
            "ents": man["entities"]}


def manifests_js(stage):
    mans = {}
    for p in sorted(Path(stage, "manifests").glob("*.json")):
        m = json.loads(p.read_text())
        mans[m["name"]] = compact(m)
    return "// generated by civ_pack.py — do not edit\nexport const MANIFESTS = " + json.dumps(mans, separators=(",", ":")) + ";\n", mans


AUTO = r'''// civtest main (BDS only): runs every check once at world load and logs [CIVTEST] JSON lines.
import { world, system } from "@minecraft/server";
import { MANIFESTS } from "./civ_manifests.js";
import { verifyFile, placeAndVerify, turnHinges, rotXZ, ROTATIONS } from "./civ_verify.js";
import "./pw_civ.js";
const log = (o) => console.warn("[CIVTEST] " + JSON.stringify(o));
async function main() {
  const dim = world.getDimension("overworld");
  try { dim.runCommand("tickingarea add 0 0 0 191 200 95 civtest true"); } catch (e) { log({ step: "tickingarea", err: String(e) }); }
  const clearAround = (at) => {                                   // many buildings share the 4 test spots: drop old entities
    for (const e of dim.getEntities({ location: { x: at.x - 2, y: at.y - 2, z: at.z - 2 }, volume: { x: 34, y: 50, z: 34 } }))
      if (e.typeId === "pw:marker" || e.typeId === "pw:hatch_lid") { try { e.remove(); } catch {} }
    try { dim.runCommand(`fill ${at.x - 1} ${at.y} ${at.z - 1} ${at.x + 30} ${at.y + 40} ${at.z + 30} air`); } catch {}
  };
  for (const [id, man] of Object.entries(MANIFESTS)) {
    log({ step: "file", ...verifyFile(id, man) });
    let ox = 64;                                                  // away from the pristine world's water near x 0..40
    for (const rot of ROTATIONS) {
      const at = { x: ox, y: 60, z: 4 };
      clearAround(at);
      await new Promise((res) => system.runTimeout(res, 2));
      const r = await placeAndVerify(id, man, dim, at, rot);
      const turned = turnHinges(dim, at, man, rot);
      await new Promise((res) => system.runTimeout(res, 3));     // entity properties apply at the end of the tick
      const hinges = [];
      const [sx, , sz] = man.size;
      for (const m of man.ents.filter((e) => e.id === "pw:hatch_lid")) {
        const [hx, hz] = rotXZ(m.cell[0], m.cell[2], sx, sz, rot);
        for (const e of dim.getEntitiesAtBlockLocation({ x: at.x + hx, y: at.y + m.cell[1] + man.datum_y, z: at.z + hz }))
          if (e.typeId === "pw:hatch_lid") hinges.push({ saved: m.hinge, now: e.getProperty("pw:hinge") });
      }
      log({ step: "place", ...r, turned, hinges });
      ox += 32;
    }
    // the same building twice: both copies must keep all their entities (entity ids are reassigned or unique)
    clearAround({ x: 64, y: 60, z: 52 }); clearAround({ x: 100, y: 60, z: 52 });
    await new Promise((res) => system.runTimeout(res, 2));
    const a = await placeAndVerify(id, man, dim, { x: 64, y: 60, z: 52 }, "None");
    const b = await placeAndVerify(id, man, dim, { x: 100, y: 60, z: 52 }, "None");
    log({ step: "twice", id, ok: a.ok && b.ok, a: a.entities, b: b.entities, aBad: a.first, bBad: b.first });
  }
  log({ step: "DONE" });
}
system.runTimeout(() => { main().catch((e) => console.warn("[CIVTEST] " + JSON.stringify({ step: "main", err: String(e) }))); }, 60);
'''


def build_bp(stage, out):
    out = Path(out)
    if out.exists():
        raise SystemExit(f"never rebuild {out}")
    (out / "scripts").mkdir(parents=True)
    shutil.copytree(Path(stage, "structures"), out / "structures")
    js, mans = manifests_js(stage)
    (out / "scripts/civ_manifests.js").write_text(js)
    shutil.copy(SRC / "civ_verify.js", out / "scripts/civ_verify.js")
    shutil.copy(SRC / "pw_civ.js", out / "scripts/pw_civ.js")
    (out / "scripts/main.js").write_text(AUTO)
    json.dump({"format_version": 2,
               "header": {"name": "PW CivTest BP (BDS only)", "description": "CIVITAS structure checks, auto-run at world load",
                          "uuid": str(uuid.uuid4()), "version": [0, 0, 1], "min_engine_version": [1, 21, 120]},
               "modules": [{"type": "script", "language": "javascript", "entry": "scripts/main.js", "uuid": str(uuid.uuid4()), "version": [0, 0, 1]},
                           {"type": "data", "uuid": str(uuid.uuid4()), "version": [0, 0, 1]}],
               "dependencies": [{"module_name": "@minecraft/server", "version": "2.3.0"}]},
              open(out / "manifest.json", "w"), indent=1)
    return list(mans)


if __name__ == "__main__":
    print(build_bp(sys.argv[1], sys.argv[2]))
