#!/usr/bin/env python3
"""habitat_table.py — every creature -> its habitat (his 16:47 ruling; profiles in habitat_profiles.py).

Line format  id: "PROFILE,PROFILE|place|abundance|herd_min-herd_max"
  place      L = land surface · A = flier (spawns on the surface, flies off) · S = shore surface (beach / ice edge)
             W = underwater (any depth) · Wb = underwater near the bottom · C = cave floor (underground) · Cw = cave water
  abundance  c = common · u = uncommon · r = rare · v = very rare   (weights in spawn_gen.py)
  SKIP: why  = no natural rule on purpose (e.g. made by another mob's growth event)
Real-world basis is the species' range and habitat; fantasy / extinct animals take their closest real analogue."""

HABITAT = {
    # ---------------- Naturalist (sf_nba) — batch 1 ----------------
    "sf_nba:alligator": "SWAMP,MANGROVE|L|u|1-2",
    "sf_nba:anglerfish": "OCEAN_DEEP|Wb|r|1-1",
    "sf_nba:ant": "GRASSLAND,TEMPERATE_FOREST,SAVANNA,DESERT,BADLANDS,JUNGLE|L|c|2-5",
    "sf_nba:anteater": "SAVANNA,JUNGLE|L|u|1-1",
    "sf_nba:badger": "TEMPERATE_FOREST,GRASSLAND|L|u|1-2",
    "sf_nba:bass": "LAKE_TEMPERATE,RIVER|W|c|2-4",
    "sf_nba:beaver": "RIVER,BOREAL,SWAMP|L|u|1-3",
    "sf_nba:beetle": "TEMPERATE_FOREST,JUNGLE,GRASSLAND,SAVANNA|L|c|1-3",
    "sf_nba:black_bear": "TEMPERATE_FOREST,BOREAL|L|u|1-2",
    "sf_nba:blobfish": "OCEAN_DEEP|Wb|r|1-1",
    "sf_nba:bluejay": "TEMPERATE_FOREST,BOREAL|A|c|1-3",
    "sf_nba:boar": "TEMPERATE_FOREST,BOREAL|L|u|2-4",
    "sf_nba:budgie": "SAVANNA,BADLANDS|A|c|3-6",
    "sf_nba:butterfly": "GRASSLAND,TEMPERATE_FOREST,JUNGLE,SAVANNA|A|c|1-3",
    "sf_nba:canary": "GRASSLAND,TEMPERATE_FOREST|A|u|2-4",
    "sf_nba:capybara": "SWAMP,JUNGLE,RIVER|L|u|2-5",
    "sf_nba:cardinal": "TEMPERATE_FOREST,SWAMP|A|c|1-2",
    "sf_nba:caterpillar": "TEMPERATE_FOREST,GRASSLAND,JUNGLE|L|u|1-2",
    "sf_nba:catfish": "RIVER,LAKE_TEMPERATE,LAKE_WARM,SWAMP_WATER|Wb|c|1-2",
    "sf_nba:cave_snake": "CAVES|C|u|1-1",
    "sf_nba:cavefish": "CAVES|Cw|u|2-4",
    "sf_nba:clam": "SEA_WARM,SEA_TEMPERATE|Wb|u|1-1",
    "sf_nba:coral_snake": "JUNGLE,SWAMP|L|u|1-1",
    "sf_nba:coyote": "GRASSLAND,DESERT,BADLANDS,BOREAL|L|u|1-3",
    "sf_nba:crab": "BEACH,MANGROVE|S|c|1-3",
    "sf_nba:crow": "GRASSLAND,TEMPERATE_FOREST,BOREAL|A|c|2-4",
    "sf_nba:deer": "TEMPERATE_FOREST,BOREAL,GRASSLAND|L|c|2-4",
    "sf_nba:desert_scorpion": "DESERT,BADLANDS|L|u|1-2",
    "sf_nba:dragonfly": "SWAMP,RIVER,GRASSLAND|A|c|1-3",
    "sf_nba:duck": "RIVER,SWAMP,GRASSLAND|L|c|2-4",
    "sf_nba:eagle": "MOUNTAIN,ALPINE_SNOW,BOREAL|A|r|1-1",
    "sf_nba:electric_eel": "LAKE_WARM|W|u|1-1",
    "sf_nba:elephant": "SAVANNA,JUNGLE|L|u|3-6",
    "sf_nba:emperor_penguin": "TUNDRA|L|u|3-8",
    "sf_nba:female_lion": "SKIP: made by sf_nba:lion's own growth event (lion.behavior.json 'into': sf_nba:female_lion)",
    "sf_nba:male_lion": "SKIP: made by sf_nba:lion's own growth event",
    "sf_nba:fennec_fox": "DESERT|L|u|1-2",
    "sf_nba:finch": "GRASSLAND,TEMPERATE_FOREST,SAVANNA|A|c|2-4",
    "sf_nba:firefly": "SWAMP,TEMPERATE_FOREST,GRASSLAND|A|c|2-6",
    "sf_nba:flamingo": "MANGROVE,SWAMP,WARM_BEACH|L|u|4-8",
    "sf_nba:flying_fish": "SEA_WARM,OCEAN_DEEP_WARM|W|c|3-6",
    "sf_nba:giant_isopod": "OCEAN_DEEP|Wb|r|1-1",
    "sf_nba:giant_salamander": "RIVER|Wb|r|1-1",
    "sf_nba:giraffe": "SAVANNA|L|u|2-4",
    "sf_nba:goose": "GRASSLAND,RIVER,SWAMP,TUNDRA|L|c|2-5",
    "sf_nba:gorilla": "JUNGLE|L|r|2-4",
    "sf_nba:great_white_shark": "SEA_TEMPERATE,SEA_COLD,OCEAN_DEEP|W|r|1-1",
    "sf_nba:grizzly_bear": "BOREAL,MOUNTAIN|L|r|1-1",
    "sf_nba:hammer_head_shark": "SEA_WARM,OCEAN_DEEP_WARM,REEF|W|r|1-3",
    "sf_nba:hamster": "GRASSLAND,SAVANNA|L|u|1-1",
    "sf_nba:hedgehog": "TEMPERATE_FOREST,GRASSLAND|L|u|1-1",
    "sf_nba:hippo": "SAVANNA,SWAMP|L|u|2-4",
    "sf_nba:hyena": "SAVANNA,DESERT|L|u|2-4",
    "sf_nba:iguana": "JUNGLE,MANGROVE,WARM_BEACH|L|u|1-2",
    "sf_nba:jellyfish": "SEA_WARM,SEA_TEMPERATE,OCEAN_DEEP|W|c|2-4",
    "sf_nba:jungle_scorpion": "JUNGLE|L|u|1-1",
    "sf_nba:kakapo": "TEMPERATE_FOREST,MOUNTAIN|L|r|1-1",
    "sf_nba:kangaroo": "SAVANNA,DESERT|L|u|2-4",
    "sf_nba:kiwi": "TEMPERATE_FOREST|L|u|1-1",
    "sf_nba:komodo_dragon": "SAVANNA,JUNGLE|L|r|1-1",
    "sf_nba:lion": "SAVANNA|L|u|2-5",
    "sf_nba:lizard": "DESERT,BADLANDS,SAVANNA|L|c|1-1",
    "sf_nba:mammoth": "TUNDRA,ALPINE_SNOW|L|r|2-4",
    "sf_nba:mole": "GRASSLAND,TEMPERATE_FOREST|L|u|1-1",
    "sf_nba:monkey": "JUNGLE|L|c|2-5",
    "sf_nba:moose": "BOREAL,SWAMP|L|u|1-2",
    "sf_nba:moray": "REEF,SEA_WARM|Wb|u|1-1",
    "sf_nba:octopus": "SEA_TEMPERATE,SEA_WARM,REEF|Wb|u|1-1",
    "sf_nba:orca": "SEA_COLD,OCEAN_DEEP_COLD,OCEAN_DEEP|W|r|2-5",
    "sf_nba:ostrich": "SAVANNA,DESERT|L|u|2-4",
    "sf_nba:otter": "RIVER,LAKE_TEMPERATE,BOREAL|L|u|1-3",
    "sf_nba:owl": "TEMPERATE_FOREST,BOREAL|A|u|1-1",
    "sf_nba:peafowl": "JUNGLE,TEMPERATE_FOREST|L|u|2-4",
    "sf_nba:piranha": "LAKE_WARM|W|c|3-6",
    "sf_nba:platypus": "RIVER,LAKE_TEMPERATE|W|r|1-1",
    "sf_nba:raccoon": "TEMPERATE_FOREST,SWAMP|L|c|1-2",
    "sf_nba:rat": "GRASSLAND,TEMPERATE_FOREST,SWAMP|L|c|1-3",
    "sf_nba:rattlesnake": "DESERT,BADLANDS,SAVANNA|L|u|1-1",
    "sf_nba:raven": "BOREAL,MOUNTAIN,TUNDRA|A|u|1-2",
    "sf_nba:ravenous_hyena": "SAVANNA,DESERT|L|r|2-4",
    "sf_nba:ray": "SEA_WARM,SEA_TEMPERATE,REEF|Wb|u|1-2",
    "sf_nba:red_panda": "BAMBOO,BOREAL|L|r|1-1",
    "sf_nba:rhino": "SAVANNA|L|r|1-2",
    "sf_nba:robin": "TEMPERATE_FOREST,GRASSLAND|A|c|1-2",
    "sf_nba:seal": "SEA_COLD,TUNDRA|S|u|2-4",
    "sf_nba:secretary_bird": "SAVANNA|L|r|1-1",
    "sf_nba:skunk": "TEMPERATE_FOREST,GRASSLAND|L|u|1-1",
    "sf_nba:sloth": "JUNGLE|L|u|1-1",
    "sf_nba:slug": "TEMPERATE_FOREST,SWAMP,GRASSLAND|L|c|1-1",
    "sf_nba:small_jellyfish": "SEA_WARM,SEA_TEMPERATE,SEA_COLD|W|c|3-6",
    "sf_nba:snail": "TEMPERATE_FOREST,GRASSLAND,SWAMP,JUNGLE|L|c|1-2",
    "sf_nba:snake": "GRASSLAND,TEMPERATE_FOREST,SAVANNA,DESERT|L|u|1-1",
    "sf_nba:sparrow": "GRASSLAND,TEMPERATE_FOREST|A|c|2-4",
    "sf_nba:spotted_moray": "REEF|Wb|u|1-1",
    "sf_nba:squirrel": "TEMPERATE_FOREST,BOREAL|L|c|1-2",
    "sf_nba:starfish": "SEA_WARM,SEA_TEMPERATE,SEA_COLD|Wb|c|1-3",
    "sf_nba:termite": "SAVANNA,JUNGLE,DESERT|L|c|2-5",
    "sf_nba:tiger": "JUNGLE,BAMBOO,BOREAL|L|r|1-1",
    "sf_nba:tortoise": "DESERT,SAVANNA,GRASSLAND|L|u|1-1",
    "sf_nba:toucan": "JUNGLE|A|c|1-2",
    "sf_nba:tree_frog": "JUNGLE,SWAMP|L|c|1-2",
    "sf_nba:turkey": "TEMPERATE_FOREST,GRASSLAND|L|u|2-5",
    "sf_nba:vulture": "SAVANNA,DESERT,BADLANDS|A|u|1-3",
    "sf_nba:walrus": "TUNDRA,SEA_COLD|S|u|2-4",
    "sf_nba:whale": "OCEAN_DEEP,SEA_COLD|W|r|1-2",
    "sf_nba:zebra": "SAVANNA|L|c|3-6",
}

# ---------------- Animals and Fauna (pw:*_anf) — batch 2a ----------------
_ANF_A = {
    "alligator_albino": "SWAMP|L|r|1-1", "alligator_american": "SWAMP,MANGROVE|L|u|1-2", "alligator_chinese": "SWAMP,RIVER|L|r|1-1",
    "bear_black": "TEMPERATE_FOREST,BOREAL|L|u|1-2", "bear_grizzly": "BOREAL,MOUNTAIN|L|r|1-1", "beaver": "RIVER,BOREAL,SWAMP|L|u|1-3",
    "beetle_atlas": "JUNGLE|L|u|1-1", "beetle_coloradopotato": "GRASSLAND|L|c|1-3", "beetle_desert": "DESERT,BADLANDS|L|c|1-2",
    "beetle_elephant": "JUNGLE,SAVANNA|L|u|1-1", "beetle_hercules": "JUNGLE|L|u|1-1", "beetle_mexicanbean": "GRASSLAND,SAVANNA|L|c|1-3",
    "beetle_mountainpine": "BOREAL,MOUNTAIN|L|c|1-3", "beetle_stag": "TEMPERATE_FOREST|L|u|1-1",
    "butterfly_adonisblue": "GRASSLAND,MOUNTAIN|A|c|1-3", "butterfly_bluemorpho": "JUNGLE|A|c|1-2",
    "butterfly_crimsonrose": "JUNGLE,SAVANNA|A|u|1-2", "butterfly_emeraldswallowtail": "JUNGLE|A|u|1-2",
    "butterfly_giantafrican": "JUNGLE|A|r|1-1", "butterfly_goliathbirdwing": "JUNGLE|A|r|1-1",
    "butterfly_monarch": "GRASSLAND,TEMPERATE_FOREST,SAVANNA|A|c|1-3", "butterfly_queenalexandra": "JUNGLE|A|v|1-1",
    "caterpillar_adonisblue": "GRASSLAND,MOUNTAIN|L|c|1-2", "caterpillar_bluemorpho": "JUNGLE|L|c|1-2",
    "caterpillar_crimsonrose": "JUNGLE,SAVANNA|L|u|1-2", "caterpillar_emeraldswallowtail": "JUNGLE|L|u|1-2",
    "caterpillar_giantafrican": "JUNGLE|L|r|1-1", "caterpillar_goliathbirdwing": "JUNGLE|L|r|1-1",
    "caterpillar_monarch": "GRASSLAND,TEMPERATE_FOREST,SAVANNA|L|c|1-2", "caterpillar_queenalexandra": "JUNGLE|L|v|1-1",
    "centipede_brown": "TEMPERATE_FOREST,GRASSLAND|L|c|1-1", "centipede_common": "TEMPERATE_FOREST,SWAMP|L|c|1-1",
    "centipede_desert": "DESERT,BADLANDS|L|u|1-1", "centipede_pacificgiant": "JUNGLE|L|u|1-1",
    "chameleon": "JUNGLE,SAVANNA|L|u|1-1",
    "crab_blue": "BEACH,MANGROVE,SWAMP|S|c|1-3", "crab_emerald": "SEA_WARM,REEF|Wb|u|1-2", "crab_king": "SEA_COLD,OCEAN_DEEP_COLD|Wb|u|1-2",
    "crab_spider": "OCEAN_DEEP,SEA_TEMPERATE|Wb|r|1-1", "crab_stone": "BEACH,MANGROVE|S|c|1-3",
    "crane_common": "GRASSLAND,SWAMP|L|u|2-4", "crane_hooden": "SWAMP,GRASSLAND|L|r|2-3", "crane_siberian": "TUNDRA,SWAMP|L|r|1-2",
    "crane_whopping": "SWAMP,GRASSLAND|L|v|1-2",
    "cricket_cave": "CAVES|C|c|1-3", "cricket_greenbush": "GRASSLAND,TEMPERATE_FOREST|L|c|1-2", "cricket_house": "GRASSLAND,SAVANNA|L|c|1-2",
    "cricket_tobacco": "SAVANNA,GRASSLAND|L|c|1-2",
    "croc_african": "SWAMP,JUNGLE|L|u|1-1", "croc_nile": "SAVANNA,SWAMP|L|u|1-2", "croc_saltwater": "MANGROVE,WARM_BEACH,SWAMP|L|r|1-1",
    "crow_carrion": "GRASSLAND,TEMPERATE_FOREST|A|c|1-3", "crow_collared": "GRASSLAND,SWAMP|A|u|1-2", "crow_hooded": "BOREAL,GRASSLAND|A|c|1-3",
    "crow_piping": "JUNGLE|A|u|1-2",
    "deer_fallow": "TEMPERATE_FOREST,GRASSLAND|L|c|2-4", "deer_red": "TEMPERATE_FOREST,MOUNTAIN,BOREAL|L|c|2-5",
    "deer_reindeer": "TUNDRA,BOREAL|L|u|3-8", "deer_roe": "TEMPERATE_FOREST,GRASSLAND|L|c|1-3",
    "dog_alsatian": "GRASSLAND,TEMPERATE_FOREST|L|r|1-2", "dog_lab_black": "GRASSLAND,TEMPERATE_FOREST|L|r|1-2",
    "dog_lab_chocolate": "GRASSLAND,TEMPERATE_FOREST|L|r|1-2", "dog_lab_golden": "GRASSLAND,TEMPERATE_FOREST|L|r|1-2",
    "dog_retriever_golden": "GRASSLAND,TEMPERATE_FOREST|L|r|1-2", "dog_retriever_white": "GRASSLAND,TEMPERATE_FOREST|L|r|1-2",
    "duck_bali": "GRASSLAND,RIVER|L|r|2-4", "duck_goldencascade": "GRASSLAND,RIVER|L|r|2-4", "duck_indianrunner": "GRASSLAND|L|r|2-4",
    "duck_kingeider": "TUNDRA,SEA_COLD|S|u|2-5", "duck_madagascar": "SWAMP|L|r|1-3", "duck_mallard": "RIVER,SWAMP,GRASSLAND|L|c|2-4",
    "duck_mandarin": "TEMPERATE_FOREST,RIVER|L|u|2-4", "duck_pekin": "GRASSLAND|L|r|2-4",
    "eagle_bald": "BOREAL,RIVER,BEACH|A|u|1-1", "eagle_blackhawk": "JUNGLE|A|u|1-1", "eagle_crowned": "JUNGLE,SAVANNA|A|r|1-1",
    "eagle_golden": "MOUNTAIN,ALPINE_SNOW,GRASSLAND|A|u|1-1", "eagle_sea": "BEACH,TUNDRA,BOREAL|A|u|1-1",
    "eagle_whitetailed": "BEACH,BOREAL,SWAMP|A|u|1-1",
    "earthworm_common": "GRASSLAND,TEMPERATE_FOREST|L|c|1-2", "earthworm_gippsland": "GRASSLAND|L|r|1-1",
    "earthworm_nightcrawler": "GRASSLAND,TEMPERATE_FOREST,SWAMP|L|c|1-2",
    "egret_great": "SWAMP,RIVER,MANGROVE|L|c|1-3", "egret_little": "SWAMP,MANGROVE,BEACH|L|c|1-3", "egret_reddish": "MANGROVE,WARM_BEACH|L|u|1-2",
    "elephant_african": "SAVANNA|L|u|3-6", "elephant_asian": "JUNGLE,BAMBOO,SAVANNA|L|u|2-5",
    "ferret_common": "GRASSLAND,TEMPERATE_FOREST|L|u|1-1", "firefly": "SWAMP,TEMPERATE_FOREST,GRASSLAND|A|c|2-6",
    "flamingo_american": "MANGROVE,WARM_BEACH,SWAMP|L|u|4-8", "flamingo_andean": "MOUNTAIN,BADLANDS|L|r|3-6",
    "flamingo_greater": "SWAMP,WARM_BEACH,MANGROVE|L|u|4-8", "flamingo_james": "MOUNTAIN,BADLANDS|L|r|3-6",
    "fly_bluebottle": "GRASSLAND,TEMPERATE_FOREST,SWAMP|A|c|1-3", "fly_dung": "GRASSLAND,SAVANNA|A|c|1-3",
    "fly_fruit": "GRASSLAND,TEMPERATE_FOREST,JUNGLE|A|c|1-3", "fly_horse": "GRASSLAND,SWAMP,SAVANNA|A|c|1-2",
    "fly_hover": "GRASSLAND,TEMPERATE_FOREST|A|c|1-3",
    "gecko_black": "DESERT,SAVANNA|L|u|1-1", "gecko_blue": "JUNGLE|L|r|1-1", "gecko_leopard": "DESERT,BADLANDS|L|u|1-1",
    "gecko_yellow": "JUNGLE,SAVANNA|L|u|1-1", "gerbil": "DESERT,SAVANNA|L|c|1-3",
    "giraffe_masai": "SAVANNA|L|u|2-4", "giraffe_nubian": "SAVANNA|L|r|2-4", "giraffe_reticulated": "SAVANNA|L|u|2-4",
    "giraffe_southafrican": "SAVANNA|L|u|2-4",
    "goose_barnacle": "TUNDRA,BEACH,GRASSLAND|L|u|3-6", "goose_canada": "GRASSLAND,RIVER,SWAMP|L|c|3-6",
    "goose_egyptian": "SAVANNA,RIVER,SWAMP|L|u|2-4", "goose_magellan": "GRASSLAND,TUNDRA|L|u|2-4", "goose_roman": "GRASSLAND|L|r|2-4",
    "grasshopper": "GRASSLAND,SAVANNA|L|c|1-3",
    "gull_blackheaded": "RIVER,SWAMP,BEACH|A|c|2-5", "gull_bonaparte": "BOREAL,BEACH|A|u|2-4", "gull_common": "BEACH,RIVER|A|c|2-5",
    "gull_greatblackbacked": "BEACH|A|u|1-2", "gull_herring": "BEACH|A|c|2-5", "gull_kittiwake": "BEACH|A|c|2-5",
    "gull_lesserblackbacked": "BEACH|A|u|1-3",
    "hamster_dwarf": "GRASSLAND,DESERT|L|u|1-1", "hamster_syrian": "DESERT,GRASSLAND|L|u|1-1",
    "hare_arctic": "TUNDRA,ALPINE_SNOW|L|c|1-2", "hare_blacktailed": "DESERT,GRASSLAND,BADLANDS|L|c|1-2",
    "hare_european": "GRASSLAND,TEMPERATE_FOREST|L|c|1-2", "hare_mountain": "MOUNTAIN,ALPINE_SNOW,BOREAL|L|u|1-2",
    "hawk_grey": "SAVANNA,DESERT|A|u|1-1", "hawk_harrier": "GRASSLAND,SWAMP|A|u|1-1", "hawk_harris": "DESERT,BADLANDS|A|u|1-2",
    "hawk_sparrow": "TEMPERATE_FOREST,BOREAL|A|u|1-1",
    "hedgehog_desert": "DESERT|L|u|1-1", "hedgehog_euro": "TEMPERATE_FOREST,GRASSLAND|L|c|1-1", "hedgehog_longeared": "DESERT,GRASSLAND|L|u|1-1",
    "hedgehog_madras": "SAVANNA|L|u|1-1", "hedgehog_southafrican": "SAVANNA,GRASSLAND|L|u|1-1",
    "heron_agami": "JUNGLE,SWAMP|L|r|1-1", "heron_black": "SWAMP,SAVANNA|L|u|1-2", "heron_blackcrowned": "SWAMP,RIVER,MANGROVE|L|c|1-2",
    "heron_greatblue": "SWAMP,RIVER,BEACH|L|c|1-1", "heron_green": "SWAMP,RIVER|L|c|1-1", "heron_grey": "RIVER,SWAMP,GRASSLAND|L|c|1-1",
    "hornet_asian": "TEMPERATE_FOREST,JUNGLE|A|u|1-3", "hornet_european": "TEMPERATE_FOREST|A|u|1-3",
    "hyena": "SAVANNA,DESERT|L|u|2-4", "iguana": "JUNGLE,MANGROVE,WARM_BEACH|L|u|1-2", "jay_brown": "JUNGLE,TEMPERATE_FOREST|A|c|2-4",
    "ladybug_15spotted": "GRASSLAND,TEMPERATE_FOREST|A|c|1-3", "ladybug_22spotted": "GRASSLAND,TEMPERATE_FOREST|A|c|1-3",
    "ladybug_7spotted": "GRASSLAND,TEMPERATE_FOREST|A|c|1-3", "ladybug_9spotted": "GRASSLAND,TEMPERATE_FOREST|A|c|1-3",
    "ladybug_harlequin": "GRASSLAND,TEMPERATE_FOREST|A|c|1-3",
    "lemming_arctic": "TUNDRA|L|c|2-5", "lemming_bog": "BOREAL,SWAMP|L|u|1-3", "lemming_norway": "TUNDRA,MOUNTAIN,ALPINE_SNOW|L|c|2-5",
    "lemming_yellowsteppe": "GRASSLAND,DESERT|L|u|1-3",
    "lemur_goldenbamboo": "BAMBOO|L|r|2-4", "lemur_mouse_brown": "JUNGLE|L|u|1-2", "lemur_mouse_grey": "JUNGLE,SAVANNA|L|u|1-2",
    "lemur_redruffed": "JUNGLE|L|r|2-4", "lemur_ringtailed": "SAVANNA,JUNGLE,BADLANDS|L|u|3-6",
}
HABITAT.update({f"pw:{k}_anf": v for k, v in _ANF_A.items()})

# ---------------- Animals and Fauna (pw:*_anf) — batch 2b ----------------
_ANF_B = {
    "lemur_sportive": "JUNGLE|L|u|1-2",
    "leopard_clouded": "JUNGLE,BAMBOO|L|r|1-1", "leopard_jungle": "JUNGLE,SAVANNA|L|r|1-1", "leopard_panther": "JUNGLE|L|r|1-1",
    "leopard_snow": "ALPINE_SNOW,MOUNTAIN|L|r|1-1",
    "lion_african": "SAVANNA|L|u|1-2", "lion_asiatic": "SAVANNA,JUNGLE|L|r|1-2", "lion_transvaal": "SAVANNA|L|u|1-2",
    "lioness_african": "SAVANNA|L|u|2-4", "lioness_asiatic": "SAVANNA,JUNGLE|L|r|2-3", "lioness_transvaal": "SAVANNA|L|u|2-4",
    "lobster": "SEA_COLD,SEA_TEMPERATE|Wb|u|1-1", "magpie": "GRASSLAND,TEMPERATE_FOREST|A|c|1-3", "mandrill": "JUNGLE|L|u|2-5",
    "meerkat": "DESERT,SAVANNA|L|c|3-6", "moose_alaskan": "BOREAL,SWAMP,TUNDRA|L|u|1-2", "moose_canadian": "BOREAL,SWAMP|L|u|1-2",
    "moth_atlas": "JUNGLE|A|r|1-1", "moth_comet": "JUNGLE|A|r|1-1", "moth_emperor": "TEMPERATE_FOREST,GRASSLAND|A|u|1-1",
    "moth_gardentiger": "GRASSLAND,TEMPERATE_FOREST|A|c|1-2", "moth_giantleopard": "TEMPERATE_FOREST,SWAMP|A|u|1-1",
    "moth_gypsy": "TEMPERATE_FOREST,BOREAL|A|c|1-3", "moth_luna": "TEMPERATE_FOREST|A|u|1-1", "moth_rosymaple": "TEMPERATE_FOREST|A|c|1-2",
    "mouse_harvest": "GRASSLAND|L|c|1-2", "mouse_house": "GRASSLAND,TEMPERATE_FOREST|L|c|1-3", "mouse_jumping": "BOREAL,GRASSLAND|L|u|1-1",
    "mouse_wood": "TEMPERATE_FOREST|L|c|1-2",
    "newt_crested": "LAKE_TEMPERATE,SWAMP|L|u|1-2", "newt_eastern": "SWAMP,TEMPERATE_FOREST|L|c|1-2", "newt_emperor": "MOUNTAIN,JUNGLE|L|r|1-1",
    "newt_firebelly": "SWAMP,BAMBOO|L|u|1-2",
    "octopus_blueringed": "REEF,SEA_WARM|Wb|r|1-1", "octopus_common": "SEA_TEMPERATE,SEA_WARM,REEF|Wb|u|1-1",
    "octopus_pacificgiant": "SEA_COLD,OCEAN_DEEP_COLD|Wb|r|1-1",
    "orangutan": "JUNGLE|L|r|1-2", "ostrich": "SAVANNA,DESERT|L|u|2-4",
    "owl_barn": "GRASSLAND,TEMPERATE_FOREST|A|u|1-1", "owl_snowy": "TUNDRA,ALPINE_SNOW|A|u|1-1", "owl_tawny": "TEMPERATE_FOREST|A|u|1-1",
    "pelican_americanwhite": "RIVER,SWAMP,BEACH|L|u|2-5", "pelican_australian": "BEACH,SWAMP|L|u|2-5", "pelican_brown": "BEACH,MANGROVE|L|c|2-5",
    "pelican_greatwhite": "SWAMP,SAVANNA|L|u|2-5",
    "pigeon_africanolive": "JUNGLE,MOUNTAIN|A|u|1-3", "pigeon_passenger": "TEMPERATE_FOREST|A|v|3-8",
    "pigeon_rock": "MOUNTAIN,BEACH,GRASSLAND|A|c|2-5", "pigeon_wood": "TEMPERATE_FOREST,GRASSLAND|A|c|1-3",
    "puffin": "BEACH,SEA_COLD|S|u|2-6", "raccoon": "TEMPERATE_FOREST,SWAMP|L|c|1-2",
    "rat_black": "GRASSLAND,TEMPERATE_FOREST|L|c|1-3", "rat_brown": "GRASSLAND,TEMPERATE_FOREST,SWAMP|L|c|1-3",
    "rat_fancy": "GRASSLAND|L|r|1-2", "rat_marsh": "SWAMP|L|c|1-3", "rat_pack": "DESERT,BADLANDS|L|u|1-2",
    "raven_common": "BOREAL,MOUNTAIN,TUNDRA|A|u|1-2", "raven_whitenecked": "SAVANNA,MOUNTAIN|A|u|1-2",
    "rhino_black": "SAVANNA|L|r|1-1", "rhino_indian": "SWAMP,SAVANNA|L|r|1-1", "rhino_sumatran": "JUNGLE|L|v|1-1", "rhino_white": "SAVANNA|L|r|1-3",
    "robin": "TEMPERATE_FOREST,GRASSLAND|A|c|1-2",
    "scorpion_deathstalker": "DESERT|L|u|1-1", "scorpion_giantdesert": "DESERT,BADLANDS|L|u|1-1", "scorpion_giantforest": "JUNGLE|L|u|1-1",
    "scorpion_indianred": "SAVANNA,DESERT|L|u|1-1",
    "seal_common": "SEA_COLD,BEACH|S|u|2-4", "seal_grey": "SEA_COLD,BEACH|S|u|2-4", "seal_harp": "TUNDRA,SEA_COLD|S|u|2-5",
    "sealion": "BEACH,SEA_TEMPERATE|S|u|2-5",
    "shark_greatwhite": "SEA_TEMPERATE,SEA_COLD,OCEAN_DEEP|W|r|1-1", "shark_hammerhead": "SEA_WARM,OCEAN_DEEP_WARM,REEF|W|r|1-3",
    "shark_lemon": "SEA_WARM,REEF|W|u|1-2", "shark_tiger": "SEA_WARM,OCEAN_DEEP_WARM|W|r|1-1",
    "shellfish_clam": "SEA_WARM,SEA_TEMPERATE|Wb|c|1-2", "shellfish_scallop": "SEA_TEMPERATE,SEA_COLD|Wb|c|1-3",
    "shellfish_seaurchin": "SEA_TEMPERATE,REEF,SEA_COLD|Wb|c|1-3", "shellfish_starfish": "SEA_WARM,SEA_TEMPERATE,SEA_COLD|Wb|c|1-3",
    "skunk": "TEMPERATE_FOREST,GRASSLAND|L|u|1-1",
    "slug_europeanred": "TEMPERATE_FOREST,GRASSLAND|L|c|1-1", "slug_leopard": "TEMPERATE_FOREST,SWAMP|L|c|1-1",
    "slug_spanish": "GRASSLAND,TEMPERATE_FOREST|L|c|1-1",
    "snail_candycane": "JUNGLE|L|u|1-1", "snail_desert": "DESERT|L|u|1-1", "snail_garden": "GRASSLAND,TEMPERATE_FOREST|L|c|1-2",
    "snail_giantafrican": "JUNGLE,SAVANNA|L|u|1-1", "snail_milk": "GRASSLAND,BEACH|L|u|1-2",
    "snake_anaconda_green": "SWAMP,JUNGLE|L|r|1-1", "snake_anaconda_yellow": "SWAMP|L|r|1-1", "snake_boa_kenyansand": "DESERT,SAVANNA|L|u|1-1",
    "snake_cobra_indian": "SAVANNA,JUNGLE|L|u|1-1", "snake_cobra_king": "JUNGLE,BAMBOO|L|r|1-1", "snake_corn": "GRASSLAND,TEMPERATE_FOREST|L|u|1-1",
    "snake_garter_butler": "GRASSLAND,SWAMP|L|c|1-1", "snake_garter_california": "GRASSLAND,TEMPERATE_FOREST|L|c|1-1",
    "snake_mamba_black": "SAVANNA|L|r|1-1", "snake_mamba_easterngreen": "JUNGLE|L|r|1-1", "snake_milk": "GRASSLAND,TEMPERATE_FOREST|L|u|1-1",
    "snake_python_greentree": "JUNGLE|L|u|1-1", "snake_python_pastel": "SAVANNA,GRASSLAND|L|u|1-1", "snake_python_royal": "SAVANNA,GRASSLAND|L|u|1-1",
    "snake_rattle_diamondback": "DESERT,BADLANDS|L|u|1-1", "snake_rattle_timber": "TEMPERATE_FOREST,MOUNTAIN|L|u|1-1",
    "snake_viper_blue": "JUNGLE|L|r|1-1", "snake_viper_horned": "DESERT|L|u|1-1",
    "snake_water_brown": "SWAMP,RIVER|L|c|1-1", "snake_water_plainbellied": "SWAMP,RIVER|L|c|1-1",
    "squirrel_grey": "TEMPERATE_FOREST|L|c|1-2", "squirrel_red": "BOREAL,TEMPERATE_FOREST|L|c|1-2",
    "stickinsect_goliath": "JUNGLE|L|u|1-1",
    "stoat_british": "GRASSLAND,TEMPERATE_FOREST|L|u|1-1", "stoat_irish": "GRASSLAND,TEMPERATE_FOREST|L|u|1-1",
    "stoat_japanese": "MOUNTAIN,BOREAL|L|u|1-1", "stoat_russian": "BOREAL,TUNDRA|L|u|1-1",
    "stork_adjutant": "SWAMP,SAVANNA|L|r|1-2", "stork_black": "TEMPERATE_FOREST,SWAMP|L|u|1-1", "stork_blacknecked": "SWAMP,MANGROVE|L|r|1-1",
    "stork_oriental": "SWAMP,RIVER|L|r|1-2", "stork_painted": "SWAMP,MANGROVE|L|u|2-4", "stork_saddlebilled": "SAVANNA,SWAMP|L|r|1-2",
    "stork_white": "GRASSLAND,SWAMP|L|c|2-4", "stork_wood": "SWAMP,MANGROVE|L|u|2-4",
    "swan_black": "SWAMP,RIVER,LAKE_TEMPERATE|L|u|2-4", "swan_white": "RIVER,SWAMP,GRASSLAND|L|u|2-4",
    "termite": "SAVANNA,JUNGLE,DESERT|L|c|2-5",
    "tern_black": "SWAMP,RIVER|A|u|2-4", "tern_caspian": "BEACH,RIVER|A|u|1-3", "tern_common": "BEACH,RIVER|A|c|2-5",
    "tern_crested": "WARM_BEACH,MANGROVE|A|u|2-4", "tern_fairy": "WARM_BEACH|A|u|1-3", "tern_largebilled": "RIVER,JUNGLE|A|u|1-3",
    "tern_sooty": "WARM_BEACH|A|c|3-6",
    "tiger_bengal": "JUNGLE,SAVANNA,BAMBOO|L|r|1-1", "tiger_siberian": "BOREAL|L|r|1-1", "tiger_southchina": "JUNGLE,BAMBOO|L|v|1-1",
    "tit_bearded": "SWAMP|A|c|2-4", "tit_blue": "TEMPERATE_FOREST,GRASSLAND|A|c|1-3", "tit_coal": "BOREAL|A|c|1-3",
    "tit_crested": "BOREAL|A|u|1-2", "tit_great": "TEMPERATE_FOREST,GRASSLAND|A|c|1-3", "tit_longtailed": "TEMPERATE_FOREST|A|c|3-6",
    "tit_marsh": "TEMPERATE_FOREST|A|u|1-2", "tit_willow": "BOREAL,SWAMP|A|u|1-2",
    "toad_africangiant": "SAVANNA,JUNGLE|L|u|1-1", "toad_canadian": "BOREAL,SWAMP|L|c|1-2", "toad_european": "TEMPERATE_FOREST,GRASSLAND|L|c|1-2",
    "toad_indian": "SAVANNA,JUNGLE|L|c|1-2", "toad_yosemite": "MOUNTAIN|L|r|1-1",
    "toucan_aracari": "JUNGLE|A|u|1-3", "toucan_channelbilled": "JUNGLE|A|u|1-2", "toucan_toco": "JUNGLE,SAVANNA|A|u|1-2",
    "vulture_king": "JUNGLE,SAVANNA|A|r|1-1", "vulture_redheaded": "SAVANNA,DESERT|A|r|1-2", "walrus": "TUNDRA,SEA_COLD|S|u|2-5",
    "wasp_paper": "GRASSLAND,TEMPERATE_FOREST|A|c|1-3", "wasp_yellowjacket": "GRASSLAND,TEMPERATE_FOREST|A|c|1-3",
    "zebra_mountain": "MOUNTAIN,SAVANNA|L|u|2-5", "zebra_plains": "SAVANNA|L|c|3-6",
}
HABITAT.update({f"pw:{k}_anf": v for k, v in _ANF_B.items()})

# ---------------- World Animals / WWA / yCreatures / Wildlife Sanctuary / Immersive Fauna — batch 3 ----------------
_PERMUTE = "SKIP: spawned inside another rule's herd (permute_type entity_type) — appears with its group"
HABITAT.update({
    "pw:aardvark_ysav": "SAVANNA|L|u|1-1", "pw:african_black_eagle_ysav": "MOUNTAIN,SAVANNA|A|r|1-1",
    "pw:african_elephant_wa": "SAVANNA|L|u|3-6", "pw:african_wild_dog_ysav": "SAVANNA|L|r|3-8", "pw:alligator_ytri": "SWAMP|L|u|1-2",
    "pw:alpaca_ytri": "MOUNTAIN,GRASSLAND|L|u|2-5", "pw:anaconda_ws": "SWAMP,JUNGLE|L|r|1-1", "pw:ant_wa": "GRASSLAND,TEMPERATE_FOREST,SAVANNA|L|c|2-5",
    "pw:anteater_ytri": "SAVANNA,JUNGLE|L|u|1-1", "pw:asian_elephant_wa": "JUNGLE,BAMBOO|L|u|2-5", "pw:baboon_ysav": "SAVANNA,MOUNTAIN|L|u|3-6",
    "pw:baby_african_black_eagle_ysav": "SKIP: the young form of the African black eagle (no natural spawn for babies)",
    "pw:baby_fisher_eagle_ysav": "SKIP: the young form of the fisher eagle (no natural spawn for babies)",
    "pw:baby_lion_ysav": _PERMUTE,
    "pw:barn_owl_ytri": "GRASSLAND,TEMPERATE_FOREST|A|u|1-1", "pw:beluga_ytri": "SEA_COLD,OCEAN_DEEP_COLD|W|u|2-5",
    "pw:bird_of_paradise_wwa": "JUNGLE|A|u|1-2", "pw:bison_ytri": "GRASSLAND,BOREAL|L|u|3-8", "pw:blue_jay_wa": "TEMPERATE_FOREST,BOREAL|A|c|1-3",
    "pw:boar_ifs": "SAVANNA|L|u|2-4", "pw:boar_wa": "TEMPERATE_FOREST,BOREAL|L|u|2-4", "pw:boar_ysav": "SAVANNA|L|u|2-4",
    "pw:bongo_ytri": "JUNGLE|L|r|1-2", "pw:buffalo_ysav": "SAVANNA,SWAMP|L|u|3-8", "pw:capuchin_wa": "JUNGLE|L|c|2-5",
    "pw:caracal_wa": "SAVANNA,DESERT|L|r|1-1", "pw:cassowary_ytri": "JUNGLE|L|r|1-1", "pw:cheetah_ysav": "SAVANNA|L|r|1-2",
    "pw:chimpanzee_wa": "JUNGLE|L|u|2-5", "pw:cobra_ysav": "SAVANNA|L|u|1-1", "pw:cougar_wa": "MOUNTAIN,BOREAL,TEMPERATE_FOREST|L|r|1-1",
    "pw:coyote_ytri": "GRASSLAND,DESERT,BADLANDS|L|u|1-3", "pw:crab_wa": "BEACH,MANGROVE|S|c|1-3", "pw:crocodile_wa": "SWAMP,MANGROVE|L|u|1-1",
    "pw:crocodile_ysav": "SAVANNA,SWAMP|L|u|1-1", "pw:deer_wa": "TEMPERATE_FOREST,BOREAL|L|c|2-4", "pw:desert_owl_ws": "DESERT|A|u|1-1",
    "pw:dik_dik_ytri": "SAVANNA|L|u|1-2", "pw:dove_wa": "GRASSLAND,TEMPERATE_FOREST|A|c|1-3", "pw:duck_wa": "RIVER,SWAMP,GRASSLAND|L|c|2-4",
    "pw:eagle_wa": "MOUNTAIN,BOREAL|A|r|1-1", "pw:elephant_ysav": "SAVANNA|L|u|3-6", "pw:emu_ytri": "SAVANNA,DESERT,GRASSLAND|L|u|2-4",
    "pw:fisher_eagle_ysav": _PERMUTE, "pw:gavial_ytri": "RIVER,SWAMP|L|r|1-1", "pw:gazelle_female_ysav": _PERMUTE,
    "pw:gazelle_ysav": "SAVANNA,DESERT|L|c|3-6", "pw:gelada_ws": "MOUNTAIN|L|u|3-6", "pw:giant_squid_wwa": "OCEAN_DEEP|W|r|1-1",
    "pw:gila_monster_ws": "DESERT,BADLANDS|L|u|1-1", "pw:giraffe_wa": "SAVANNA|L|u|2-4", "pw:giraffe_ysav": "SAVANNA|L|u|2-4",
    "pw:gnu_ysav": "SAVANNA|L|c|4-8", "pw:gorilla_wa": "JUNGLE|L|r|2-4", "pw:gorilla_ytri": "JUNGLE|L|r|2-4",
    "pw:hammerhead_shark_wa": "SEA_WARM,REEF,OCEAN_DEEP_WARM|W|r|1-3", "pw:hedgehog_wa": "TEMPERATE_FOREST,GRASSLAND|L|u|1-1",
    "pw:honey_badger_ysav": "SAVANNA,DESERT|L|u|1-1", "pw:hornbill_ws": "JUNGLE,SAVANNA|A|u|1-2",
    "pw:hummingbird_ytri": "JUNGLE,TEMPERATE_FOREST,GRASSLAND|A|c|1-2", "pw:hyena_ysav": "SAVANNA|L|u|2-4", "pw:hyenas_wa": "SAVANNA,DESERT|L|u|2-4",
    "pw:impala_female_ysav": _PERMUTE, "pw:impala_ysav": "SAVANNA|L|c|3-6", "pw:jellyfish_ytri": "SEA_WARM,SEA_TEMPERATE,SEA_COLD|W|c|2-4",
    "pw:jerboa_wwa": "DESERT|L|c|1-2", "pw:kakapo_wwa": "TEMPERATE_FOREST,MOUNTAIN|L|r|1-1", "pw:koala_ytri": "SAVANNA,TEMPERATE_FOREST|L|u|1-1",
    "pw:kob_female_ysav": _PERMUTE, "pw:kob_ysav": "SAVANNA,SWAMP|L|c|3-6", "pw:komodo_dragon_wa": "SAVANNA,JUNGLE|L|r|1-1",
    "pw:komodo_dragon_ytri": "SAVANNA,JUNGLE|L|r|1-1", "pw:kudu_female_ysav": _PERMUTE, "pw:kudu_ysav": "SAVANNA|L|u|2-4",
    "pw:lantern_fish_wa": "OCEAN_DEEP|W|c|4-8", "pw:lemur_ytri": "JUNGLE,SAVANNA|L|u|2-4", "pw:leopard_ysav": "SAVANNA,JUNGLE|L|r|1-1",
    "pw:lion_wa": "SAVANNA|L|u|2-4", "pw:lion_ysav": _PERMUTE, "pw:lioness_ysav": "SAVANNA|L|u|2-4", "pw:lynx_ws": "BOREAL,MOUNTAIN|L|r|1-1",
    "pw:manatee_ytri": "SEA_WARM,MANGROVE,WARM_RIVER|W|u|1-2", "pw:meerkat_ytri": "DESERT,SAVANNA|L|c|3-6",
    "pw:mole_ytri": "GRASSLAND,TEMPERATE_FOREST|L|u|1-1", "pw:monitor_lizard_ysav": "SAVANNA,JUNGLE,MANGROVE|L|u|1-1",
    "pw:monkey_ws": "JUNGLE|L|c|2-5", "pw:naja_spit_ysav": "SKIP: the spitting cobra's venom projectile, not a creature",
    "pw:orca_wa": "SEA_COLD,OCEAN_DEEP|W|r|2-5", "pw:orca_wwa": "SEA_COLD,OCEAN_DEEP|W|r|2-5", "pw:orca_ytri": "SEA_COLD,OCEAN_DEEP|W|r|2-5",
    "pw:oryx_ysav": "DESERT,SAVANNA|L|u|2-5", "pw:ostrich_wa": "SAVANNA,DESERT|L|u|2-4", "pw:ostrich_ws": "SAVANNA,DESERT|L|u|2-4",
    "pw:ostrich_ysav": "SAVANNA,DESERT|L|u|2-4", "pw:otter_ytri": "RIVER,LAKE_TEMPERATE,BOREAL|L|u|1-3",
    "pw:owl_ytri": "TEMPERATE_FOREST,BOREAL|A|u|1-1", "pw:pangolin_ysav": "SAVANNA,JUNGLE|L|r|1-1",
    "pw:platypus_ytri": "RIVER,LAKE_TEMPERATE|W|r|1-1", "pw:prairie_dog_wwa": "GRASSLAND|L|c|3-6",
    "pw:raccoon_wwa": "TEMPERATE_FOREST,SWAMP|L|c|1-2", "pw:rat_wa": "GRASSLAND,TEMPERATE_FOREST|L|c|1-3",
    "pw:rattlesnake_ws": "DESERT,BADLANDS|L|u|1-1", "pw:red_panda_wa": "BAMBOO,BOREAL|L|r|1-1", "pw:red_panda_wwa": "BAMBOO,BOREAL|L|r|1-1",
    "pw:rhino_wa": "SAVANNA|L|r|1-2", "pw:rhino_ysav": "SAVANNA|L|r|1-2", "pw:river_dolphin_ytri": "LAKE_WARM|W|r|1-3",
    "pw:roadrunner_wwa": "DESERT,BADLANDS|L|u|1-1", "pw:sable_antelope_ysav": "SAVANNA|L|u|3-6", "pw:saiga_wwa": "GRASSLAND,DESERT|L|u|4-8",
    "pw:seal_wwa": "SEA_COLD,BEACH|S|u|2-4", "pw:serval_ysav": "SAVANNA,SWAMP|L|r|1-1", "pw:shark_wa": "SEA_TEMPERATE,SEA_WARM|W|r|1-1",
    "pw:shoebill_wwa": "SWAMP|L|r|1-1", "pw:shrimp_wa": "SEA_WARM,SEA_TEMPERATE|Wb|c|3-8", "pw:skunk_ytri": "TEMPERATE_FOREST,GRASSLAND|L|u|1-1",
    "pw:snake_coral_wa": "JUNGLE,SWAMP|L|u|1-1", "pw:snake_scarlet_wa": "TEMPERATE_FOREST,GRASSLAND|L|u|1-1",
    "pw:snake_wa": "GRASSLAND,DESERT,JUNGLE,SWAMP,BADLANDS|L|u|1-1", "pw:snapping_turtle_wwa": "SWAMP,RIVER|L|u|1-1",
    "pw:snow_leopard_wa": "ALPINE_SNOW,MOUNTAIN|L|r|1-1", "pw:stingray_wa": "SEA_WARM,REEF|Wb|u|1-2", "pw:stingray_wwa": "SEA_WARM,REEF|Wb|u|1-2",
    "pw:stingray_ytri": "SEA_WARM,REEF|Wb|u|1-2", "pw:swan_wwa": "RIVER,SWAMP|L|u|2-4", "pw:swordfish_wa": "SEA_WARM,SEA_TEMPERATE,OCEAN_DEEP|W|u|1-2",
    "pw:tapir_ws": "JUNGLE|L|u|1-1", "pw:tiger_shark_wa": "SEA_WARM,OCEAN_DEEP_WARM|W|r|1-1", "pw:tiger_wa": "JUNGLE,BAMBOO|L|r|1-1",
    "pw:tiger_ws": "JUNGLE,BAMBOO|L|r|1-1", "pw:toadfish_wwa": "SEA_WARM,SEA_TEMPERATE|Wb|u|1-1", "pw:tortoise_ysav": "SAVANNA,DESERT|L|u|1-1",
    "pw:toucan_wa": "JUNGLE|A|u|1-2", "pw:toucan_ytri": "JUNGLE|A|u|1-2", "pw:tsessebe_ysav": "SAVANNA|L|u|3-6",
    "pw:turkey_wa": "TEMPERATE_FOREST,GRASSLAND|L|u|2-5", "pw:viper_ysav": "SAVANNA,DESERT|L|u|1-1",
    "pw:whale_wa": "OCEAN_DEEP,SEA_COLD|W|r|1-2", "pw:whale_wwa": "OCEAN_DEEP,SEA_COLD|W|r|1-2",
    "pw:white_lion_ysav": _PERMUTE, "pw:white_lioness_ysav": _PERMUTE, "pw:white_shark_wa": "SEA_TEMPERATE,SEA_COLD|W|r|1-1",
    "pw:white_tiger_wa": "JUNGLE,BAMBOO|L|v|1-1", "pw:yak_ws": "ALPINE_SNOW,MOUNTAIN|L|u|3-6", "pw:zebra_wa": "SAVANNA|L|c|3-6",
    "pw:zebra_ysav": "SAVANNA|L|c|3-6",
})
