#!/usr/bin/env python3
"""palace_beds.py — 1.3.229 ROLE BEDS (his 14:07): the palace's beds by piece and room role, from palacegen's model
(the bed() calls carry the room role; the structures are unchanged — this script proves it by cutting the model and
comparing each piece's bytes with the pieces the stages were made from). Output: JSON on stdout + --js writes
tools/bp02_src_228/pw_civ_court_data.js (the clock's table)."""
import json, sys
from pathlib import Path
sys.path.insert(0, "/home/claude/tools")
import palacegen as PG  # noqa: E402

p = PG.build()
counts = {}
lost = []
for b in p.bed_roles:
    e = p.st.get(b["x"], p.y(b["feet"]), b["z"])
    if not e or not str(e[0]).endswith(":bed"):
        lost.append(b); continue                       # a later room overwrote this bed: not a bed in the palace

    q = ("n" if b["x"] >= 64 else "s") + ("e" if b["z"] >= 64 else "w")
    counts.setdefault(q, {}).setdefault(b["role"], 0)
    counts[q][b["role"]] += 1
pieces = PG.cut(p)
same = {}
for q, (st, _marks) in pieces.items():
    f = PG.OUT / "structures" / f"mvv_palace_{q}_a_r1.mcstructure"
    same[q] = f.exists() and f.read_bytes() == st.to_bytes()
out = {"beds": len(p.bed_roles) - len(lost), "overwritten": lost, "byPiece": counts, "piecesUnchanged": same}
print(json.dumps(out, indent=1))
if "--js" in sys.argv:
    js = ("// pw_civ_court_data.js — GENERATED by tools/palace_beds.py (1.3.229 role beds): the palace pieces' beds by room role.\n"
          "// A bed = one double bed (2 bed blocks). Roles: lord, noble, servant, guard, clerk, cell (never a home).\n"
          f"export const PALACE_BEDS = {json.dumps(counts, sort_keys=True)};\n")
    Path("/home/claude/tools/bp02_src_228/pw_civ_court_data.js").write_text(js)
    print("wrote pw_civ_court_data.js")
