"""Writes _docs/palace/PALACE-II-DESIGN-2026-10-07.md from the live palacegen2 model (rooms, secrets, spirals, notes),
so the design doc can never drift from the generator. Usage: python3 tools/palace2_designdoc.py"""
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import palacegen2 as P2  # noqa: E402

OUT = Path("/home/claude/_docs/palace/PALACE-II-DESIGN-2026-10-07.md")
LEVELS = [("B2", "B2 - tunnels and sewers (walk -12)"), ("B1", "B1 - cellars, Pozzi, crypt, grotto (walk -7)"),
          ("G", "Ground (walk 0)"), ("N", "Etage noble - state floor (walk 6)"),
          ("E", "Entresol / mezzanines (walk 11)"), ("A", "Attic (walk 15)")]


def cell(text):
    """Markdown-table-safe text."""
    return str(text).replace("|", "/").replace("\n", " ")


def main():
    p = P2.build()
    by_level = defaultdict(list)
    for r in p.rooms:
        by_level[r["level"]].append(r)
    sourced = sum(1 for r in p.rooms if r.get("imitates"))
    out = ["# PALACE II - DESIGN (2026-10-07)", "",
           "Generated by `tools/palace2_designdoc.py` from `tools/palacegen2.py` - regenerate, never hand-edit.",
           "Research and full source list: `_docs/palace/PALACE-II-RESEARCH-2026-10-06.md` (sections 1-5, Sources).",
           "Plans and sections: `_docs/palace/palace2/` (plans viewed from above, street/gate LEFT = west, model north UP;",
           "sections seen from the south, looking north).", "",
           "## Rulings applied", "",
           "- D-C1006-PAL2: 4 x 4 pieces = 256 x 256; real-palace blueprints incl. secret hallways, doors, stairs and underground",
           "  passages; secret stairs = narrow spiral design A; royal nursery for 4 children, beds against walls; secrets used",
           "  by lord / family / guards / servants and discoverable by the player.",
           "- 2026-10-07 (Abs0lum): the solid plinth under the cross salon is a ground-floor room (plate room); the two long",
           "  wings are named north wing (model z 16..39) and south wing (model z 216..239).",
           "- Engine laws: headroom >= 2 blocks, custom stairs laid last, structures never mirrored.", "",
           f"## Totals", "",
           f"- Rooms: {len(p.rooms)} ({sourced} carry a real-palace precedent; the rest are ordinary service/family rooms of",
           "  the same type, generated in series).",
           f"- Hidden network elements: {len(p.secrets)}. Spiral / vice stairs: {len(p.spirals)}.",
           "- Verification: `python3 tools/palace2_verify.py` (12 tests).", "",
           "## Massing notes (generator)", ""]
    out += [f"- {cell(n)}" for n in p.notes]
    out += ["", "## Hidden network - every secret and its precedent", "",
            "| id | element | precedent (real palace) | how it works in-game | public side (x,f,z) | hidden side (x,f,z) | mode |",
            "|---|---|---|---|---|---|---|"]
    for s in p.secrets:
        out.append(f"| {s['id']} | {cell(s['element'])} | {cell(s['precedent'])} | {cell(s['how'])} | "
                   f"{s.get('public')} | {s.get('hidden')} | {s.get('mode')} |")
    out += ["", "## Spiral and vice stairs", "", "| label | design | material | hand | floors served |", "|---|---|---|---|---|"]
    for sp in p.spirals:
        out.append(f"| {cell(sp.get('label'))} | {sp.get('design')} | {sp.get('pal')} | {sp.get('hand')} | "
                   f"{sp.get('f0')} -> {sp.get('floors')} |")
    for lv, title in LEVELS:
        rooms = by_level.get(lv, [])
        if not rooms:
            continue
        out += ["", f"## Rooms - {title} ({len(rooms)})", "",
                "| room | box x0..x1, z0..z1 | hidden | precedent |", "|---|---|---|---|"]
        for r in rooms:
            b = r["box"]
            out.append(f"| {cell(r['name'])} | {b[0]}..{b[1]}, {b[2]}..{b[3]} | {'yes' if r.get('hidden') else ''} | "
                       f"{cell(r.get('imitates') or '-')} |")
    out += ["", "## Design choices not taken from a source", "",
            "- Plate room (silver pantry under the cross salon): use chosen by Claude to fill the former solid plinth;",
            "  the household plate room is a standard service-floor room type, not copied from one named palace.",
            "- Rooms marked '-' in the precedent column are generated series rooms (servants' rooms, cellars, stores).", ""]
    OUT.write_text("\n".join(out))
    print(OUT, len(out), "lines")


if __name__ == "__main__":
    main()
