source=skybox:overworld/001-100_sky/sky001_stars_bright.png
startFadeIn=11:58
endFadeIn=11:59
startFadeOut=12:00
endFadeOut=12:01
blend=alpha
rotate=true
speed=1
axis=0.0 0.0 -1.0
weather=clear rain thunder