source=skybox:overworld/001-100_sky/sky023_mask_normal5.png
blend=alpha
startFadeIn=3:30
endFadeIn=3:42
startFadeOut=20:18
endFadeOut=20:30
rotate=true
speed=0.866
axis=0.0 -1.0 0.0
transition=10
weather=clear
heights=0-254
biomes=deep_dark dripstone_caves lush_caves mangrove_swamp pale_garden swamp swamp_hills