source=skybox:overworld/001-100_sky/sky026_mask_snow.png
blend=alpha
startFadeIn=3:30
endFadeIn=3:42
startFadeOut=20:18
endFadeOut=20:30
rotate=true
speed=1.732
axis=0.0 -1.0 0.0
transition=10
weather=rain thunder
heights=0-254
biomes=deep_frozen_ocean frozen_ocean frozen_river ice_spikes snowy_beach snowy_plains snowy_taiga snowy_tundra grove