source=skybox:overworld/001-100_sky/sky031_shooting_star1_o.png
blend=add
startFadeIn=20:27
endFadeIn=20:28
startFadeOut=20:28
endFadeOut=20:29
rotate=true
speed=211
axis=0.5 0.866025403 0.0
weather=clear