source=skybox:overworld/001-100_sky/sky030_sunset_sunrise_low_o.png
blend=add
startFadeIn=3:42
endFadeIn=4:42
startFadeOut=5:42
endFadeOut=6:42
rotate=false
transition=10
weather=clear rain thunder
heights=0-254