source=skybox:overworld/001-100_sky/sky038_mask_high.png
startFadeIn=11:58
endFadeIn=11:59
startFadeOut=12:00
endFadeOut=12:01
blend=alpha
rotate=false
weather=clear rain thunder
heights=255-318