source=skybox:overworld/001-100_sky/sky039_sunset_sunrise_high.png
blend=screen
startFadeIn=17:18
endFadeIn=18:18
startFadeOut=19:18
endFadeOut=20:18
rotate=false
transition=10
weather=clear rain thunder
heights=255-318