// pw_civ_court_data.js — the palace pieces' beds by room role. A bed = one double bed (2 bed blocks).
// Roles: lord, noble, servant, guard, clerk, cell (never a home), child (a children's bed, never a role slot).
// 1.3.232 (#21, HOOK-PROPOSAL Part B): PALACE II's beds are ADDED beside the 2 x 2 palace's — a saved world's 2 x 2 palace
// keeps its role beds (pw_civ_court.js bedsOfPiece reads by the piece key; the keys never collide).
// PALACE_BEDS_1 — GENERATED by tools/palace_beds.py (1.3.229 role beds): the 2 x 2 palace, keyed sw se nw ne.
export const PALACE_BEDS_1 = {"ne": {"child": 4, "guard": 4, "lord": 1, "noble": 3, "servant": 4}, "nw": {"child": 3, "noble": 3, "servant": 12}, "se": {"child": 5, "clerk": 7, "guard": 3, "noble": 5, "servant": 22}, "sw": {"cell": 4, "clerk": 7, "guard": 9, "servant": 16}};
// PALACE_BEDS_2 — GENERATED by tools/palace2_hookdata.py (PALACE II, 4 x 4 pieces), keyed "rc" (r = depth from the gate
// side 0..3, c = frontage 0..3). D-GH1007-LORDBEDS: two lord beds (21: the lord's state bedchamber, 22: the consort's).
export const PALACE_BEDS_2 = {"00": {"clerk": 6, "guard": 6, "servant": 52}, "01": {"guard": 4}, "02": {"guard": 4}, "03": {"child": 16, "clerk": 6, "noble": 8, "servant": 22}, "10": {"cell": 3, "child": 2, "noble": 1, "servant": 41}, "11": {"child": 4, "guard": 2, "noble": 1, "servant": 1}, "12": {"child": 2, "guard": 2, "noble": 1}, "13": {"child": 10, "noble": 5, "servant": 14}, "20": {"cell": 5, "guard": 2, "servant": 3}, "21": {"child": 2, "guard": 4, "lord": 1, "servant": 14}, "22": {"guard": 2, "lord": 1, "servant": 29}, "23": {"servant": 3}, "30": {}, "31": {}, "32": {"servant": 16}, "33": {"servant": 6}};
export const PALACE_BEDS = { ...PALACE_BEDS_1, ...PALACE_BEDS_2 };
