source=skybox:overworld/001-100_sky/sky019_mask_normal1.png
blend=alpha
startFadeIn=3:30
endFadeIn=3:42
startFadeOut=20:18
endFadeOut=20:30
rotate=true
speed=0.866
axis=0.0 -1.0 0.0
transition=10
weather=clear
heights=0-254
biomes=forest birch_forest birch_forest_hills cherry_grove dark_forest dark_forest_hills flower_forest meadow mushroom_fields plains river sunflower_plains taiga tall_birch_forest tall_birch_hills windswept_forest