source=skybox:overworld/001-100_sky/sky015_sun_glare.png
blend=add
startFadeIn=6:00
endFadeIn=7:00
startFadeOut=17:00
endFadeOut=18:00
rotate=true
speed=1
axis=0.0 0.0 1.0
transition=10
weather=clear rain thunder
heights=0-254