source=skybox:overworld/001-100_sky/sky029_day.png
blend=screen
startFadeIn=5:42
endFadeIn=6:42
startFadeOut=17:18
endFadeOut=18:18
rotate=false
transition=10
weather=clear rain thunder
heights=0-254