source=skybox:overworld/001-100_sky/sky025_mask_clear.png
blend=alpha
startFadeIn=3:30
endFadeIn=3:42
startFadeOut=20:18
endFadeOut=20:30
rotate=true
speed=2
axis=0.0 -1.0 0.0
transition=10
weather=clear
heights=0-254
biomes=desert desert_hills desert_lakes