source=skybox:overworld/001-100_sky/sky037_meteor_shower3_o.png
blend=add
startFadeIn=3:26
endFadeIn=3:29
startFadeOut=3:34
endFadeOut=3:37
rotate=true
speed=250
axis=0.76604 0.52654 -0.36869
weather=clear
daysLoop=8
days=4