source=skybox:overworld/001-100_sky/sky036_meteor_shower2_o.png
blend=add
startFadeIn=3:13
endFadeIn=3:16
startFadeOut=3:47
endFadeOut=3:50
rotate=true
speed=210
axis=0.64279 0.69427 -0.32374
weather=clear
daysLoop=8
days=4