source=skybox:overworld/001-100_sky/sky033_shooting_star3_o.png
blend=add
startFadeIn=3:42
endFadeIn=4:31
startFadeOut=4:31
endFadeOut=4:32
rotate=true
speed=273
axis=-0.57729 -0.577364 -0.577379
weather=clear