source=skybox:overworld/001-100_sky/sky032_shooting_star2_o.png
blend=add
startFadeIn=22:52
endFadeIn=22:53
startFadeOut=22:53
endFadeOut=22:54
rotate=true
speed=281
axis=-0.358785 0.660076 -0.659905
weather=clear